//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by YDUIQuestionVault.rc
//
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDD_YDUIQUESTIONVAULT_FORM_QUESTION_VAULT_CLASSICATION 311
#define IDD_YDUIQUESTIONVAULT_FORM_QUESTION_TYPE 312
#define IDD_YDUIQUESTIONVAULT_FORM_QUESTION_VAULT_BASE 316
#define IDD_YDUIQUESTIONVAULT_FORM_QUESTION_VAULT_KNOWLEDGE 321
#define IDD_DIALOG_QUESTION_VAULT_QTYPE 322
#define IDD_YDUIQUESTIONVAULT_FORM_QUESTION_VAULT_QTYPE 322
#define IDD_YDUIQUESTIONVAULT_DIALOG_KNOWLEDGE 323
#define IDD_YDUIQUESTIONVAULT_DIALOG_CHOICE_QUESTION 324
#define IDD_YDUIQUESTIONVAULT_FORM_ARTQICLEQUESTION 325
#define IDD_YDUIQUESTIONVAULT_FORM_QUESTIONLIST 330
#define IDD_YDUIQUESTIONVAULT_DIALOG_COMPOSITION_QUESTION 334
#define IDD_YDUIQUESTIONVAULT_DIALOG_TRANSLATION_QUESTION 335
#define IDD_YDUIQUESTIONVAULT_DIALOG_READ_QUESTION 336
#define IDD_YDUIQUESTIONVAULT_DIALOG_QVIEW 341
#define IDD_YDUIQUESTIONVAULT_DIALOG_PAPERFOLDER 342
#define IDC_EDIT_NAME                   1000
#define IDC_EDIT_CODE                   1001
#define IDC_EDIT_CREATOR                1002
#define IDC_EDIT_CREATER                1003
#define IDC_EDIT_CREATE_DATE            1003
#define IDC_EDIT_DESC                   1004
#define IDC_EDIT_DESCRIPTION            1004
#define IDC_EDIT_CQ_ANSWER              1004
#define IDC_EDIT_QVC_CREATE_DATE        1005
#define IDC_EDIT_QVB_CREATE_DATE        1005
#define IDC_EDIT_CQ_CREATOR             1005
#define IDC_EDIT_PFNAME                 1005
#define IDC_EDIT_CQ_TITLE               1006
#define IDC_EDIT_PFCREATOR              1006
#define IDC_EDIT_CQ_CREATE_DATE         1007
#define IDC_EDIT_CQ_ANSWER_DESC         1008
#define IDC_EDIT_PFDESC                 1008
#define IDC_LIST_KNOWLEDGE              1009
#define IDC_LIST_QTYPE_EXIST            1011
#define IDC_EDIT_PFCREATEDATE           1012
#define IDC_LIST_QTYPE_ALL              1012
#define ID_BUTTON_NEW                   1014
#define ID_BUTTON_MODIFY                1015
#define ID_BUTTON_DEL                   1016
#define IDC_BUTTON_ADD                  1017
#define IDC_BUTTON_DEL                  1018
#define IDC_BUTTON_REMOVE               1018
#define IDC_BUTTON_ADD2                 1018
#define IDC_COMBO_CQ_HARDLEVEL          1021
#define IDC_EDIT_CQ_CODE                1022
#define IDC_RICHEDIT_AC_ARTICLE         1024
#define IDC_COMBO_AQ_HARDLEVEL          1026
#define IDC_EDIT_AQ_CREATOR             1027
#define IDC_EDIT_AQ_CREATE_DATE         1028
#define IDC_EDIT_QT_NAME                1029
#define IDC_EDIT_QT_CREATER             1030
#define IDC_EDIT_QT_CREATE_DATE         1031
#define IDC_EDIT_QT_DESC                1032
#define IDC_LIST_QL_QUESTION            1035
#define IDC_STATIC_GRID                 1036
#define IDC_BTN_GP_OK                   1038
#define IDC_BTN_GP_CANCEL               1040
#define IDC_BTN_ADD                     1041
#define IDC_BTN_ADDALL                  1042
#define IDC_BTN_DEL                     1043
#define IDC_BTN_DELALL                  1044
#define IDC_LIST_KPINDB                 1045
#define IDC_LIST_KPINPAPER              1046
#define IDC_LIST_RElATE_KNOWLEDGE       1047
#define IDC_EDIT_FILE                   1049
#define IDC_EDIT_QL_QUERY_TOTAL         1049
#define IDC_EDIT_Paper                  1050
#define IDC_RICHEDIT_TITLE              1057
#define IDC_BUTTON_INPUT                1058
#define IDC_RICHEDIT_ANSWER             1058
#define IDC_BUTTON_CQ_REMOVEKP          1058
#define IDC_BUTTON_SEL_FILE             1058
#define IDC_BUTTON_QL_QUERY_DEL         1058
#define IDC_RADIO_PICTURE               1059
#define IDC_RADIO_SOUND                 1060
#define IDC_RADIO_VOD                   1061
#define IDC_BUTTON_QL_ADD               1064
#define IDC_BUTTON_QL_MODIFY            1065
#define IDC_BUTTON_QL_DEL               1066
#define IDC_STATIC_QL_GRID              1067
#define IDC_BUTTON_QL_QUERY_ADD         1068
#define IDC_BUTTON_QL_QUERY_CLEAR       1069
#define IDC_BUTTON_QL_QUERY_QUERY       1070
#define IDC_BUTTON_QL_DEL2              1071
#define IDC_BUTTON_QL_OUTPUT            1071
#define IDC_BUTTON_QL_QUERY_PREV        1075
#define IDC_BUTTON_QL_QUERY_NEXT        1076
#define IDC_BUTTON_QL_QUERY_END         1077
#define IDC_EDIT_QL_QUERY_PAGENUM       1078
#define IDC_BUTTON_QL_QUERY_BEGIN       1079
#define IDC_BUTTON_CQ_ADD               1080
#define IDC_BUTTON_CQ_MODIFY            1081
#define IDC_BUTTON_CQ_CLOSE             1082
#define IDC_LIST_CHOICE_QUESTION        1082
#define IDC_BUTTON_NEW_QUESTION         1083
#define IDC_LIST_CQ_KPALL               1084
#define IDC_BUTTON_MODIFY_QUESTION      1084
#define IDC_LIST_CQ_KPRELATED           1085
#define IDC_LIST_CQ_KPALL2              1085
#define IDC_BUTTON_CQ_ADDKP             1086
#define IDC_LIST_CQ_KPRELATED2          1086
#define IDC_BUTTON_DEL_QUESTION         1087
#define IDC_BUTTON_ADDKP                1088
#define IDC_BUTTON_EXPORT               1090
#define IDC_BUTTON_REMOVEKP             1091
#define IDC_LIST_KPALL                  1092
#define IDC_LIST_KPRELATED              1093
#define IDC_BUTTON_RESEL                1096
#define IDC_STATIC_PREV                 1097
#define IDC_RICHEDIT_QUESTION           1100
#define IDC_CMB_PAPERTEMP               1102
#define IDC_BTN_OBSOLETE                1103
#define IDC_TREE_PAPERFOLDER            1104
#define IDC_BCGPGRIDCTRL_ID_INPLACE     1105
#define IDC_PAPER_GCL_PREVIEW           1106
#define IDC_CQ_GCL_OPTION               1107
#define IDC_QL_GCL_QUERYCONN            1108
#define IDS_YDUIQUESTIONVAULT_PAPERMGR_ROOT 15000
#define IDC_EDIT_PAPERNAME              15000
#define IDD_YDUIQUESTIONVAULT_FORM_QUESTION_KNOWLEDGE 15001
#define IDC_EDIT_PAPERCREATOR           15001
#define IDC_EDIT_PAPERCREATEDATE        15002
#define IDD_YDUIQUESTIONVAULT_DIALOG_FACTORINFO_CONFIG 15002
#define IDC_EDIT_PAPERDESC              15003
#define IDC_LIST1                       15004
#define IDC_LIST_PAPERS                 15004
#define IDC_BTN_OUTPUT                  15005
#define IDC_CHECK1                      15006
#define IDC_STATIC_BK                   15007
#define IDC_BUTTON_FACTORINFO_CONIFG    15008
#define IDD_YDMAIN_DIALOG_PAPERFOLDER   30011
#define IDD_YDUIQUESTIONVAULT_FORM_PAPERFOLDER 30011
#define IDD_YDUIQUESTIONVAULT_FORM_GENERATEPAPER 30012
#define IDD_YDUIQUESTIONVAULT_FORM_PAPERFOLDER1 30013
#define IDD_YDUIQUESTIONVAULT_FORM_PAPER 30013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        15003
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         15010
#define _APS_NEXT_SYMED_VALUE           15000
#endif
#endif
