//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ExerciseMain.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STRING101                   101
#define IDS_RIBBON_LOAD_VAULT           101
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ExerciseMainTYPE            130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_MAIN                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_NEW_EXERCISE         291
#define IDS_RIBBON_NEW_EXAM             292
#define IDS_RIBBON_LOAD_EXERCISE        293
#define IDS_RIBBON_EXERCISE             294
#define IDS_RIBBON_EXAM                 295
#define IDS_RIBBON_OPERATOR             296
#define IDS_RIBBON_SETTING              297
#define IDS_RIBBON_OPTION               298
#define IDS_RIBBON_SET_WORKSPACE        299
#define IDS_RIBBON_SET_TIME             300
#define IDS_RIBBON_SET_EXERCISECFG      301
#define IDS_RIBBON_SET_EXERCISECFG2     302
#define IDS_RIBBON_SET_EXAMCFG          302
#define IDS_EDIT_MENU                   306
#define IDB_PNG1                        310
#define IDB_BITMAP1                     311
#define IDD_DLG_EM_EXERCISE             312
#define IDR_HTML_EXERCISEDLG            313
#define IDB_BITMAP2                     313
#define IDB_BITMAP_Abort                313
#define IDD_DLG_EM_EXAM                 313
#define IDD_DLG_EM_CFG_EXAM_TIME        314
#define IDB_BITMAP_BEGIN                314
#define IDB_BITMAP_NEXT                 315
#define IDB_BITMAP_PREV                 316
#define IDB_BITMAP_STOP                 317
#define IDB_BITMAP_STDANS               318
#define IDB_BITMAP_STUANS               319
#define IDB_BITMAP5                     320
#define IDB_BITMAP_FINISH               320
#define IDB_BITMAP_TREENODE             323
#define IDD_DLG_ARTICLE                 324
#define IDD_DIALOG_DEFAULT              325
#define IDD_DLG_EM_STDANSWER            326
#define IDD_DIALOG2                     327
#define IDD_DIALOG_STUDENT_ANSWER       327
#define IDD_DLG_QUESTION_4              328
#define IDD_DLG_QUESTION_AREA           329
#define IDD_DLG_ARTICLE1                330
#define IDD_DLG_LISTEN                  330
#define IDD_DLG_WRITE                   331
#define IDD_DLG_CHOICE                  332
#define IDD_DLG_QUESTION_1              333
#define IDD_DLG_QUESTION_0              334
#define IDD_DLG_LISTEN_ARTICLE          335
#define IDD_DLG_SEL_LOG                 336
#define IDD_DLG_EXISICE_MARK            337
#define IDD_DIALOG1                     338
#define IDD_DIALOG_RENAME               338
#define IDD_DLG_EM_CFG_QUESTION_2       339
#define IDB_BITMAP_MAINTREE             340
#define IDD_DLG_PERSIONINFO_VIEW        341
#define IDC_TREE_EM_QUESTION            1000
#define IDC_BTN_EM_PREV                 1001
#define IDC_BTN_EM_NEXT                 1002
#define IDC_BTN_EM_BEGIN                1003
#define IDC_BTN_EM_STOP                 1004
#define IDC_BTN_EM_ABORT                1005
#define IDC_RICHEDIT21                  1007
#define IDC_RICHEDIT_ARTICAL            1007
#define IDC_RICHEDIT_ARTICLE            1007
#define IDC_RICHEDIT22                  1008
#define IDC_RICHEDIT_ANSWER             1008
#define IDC_BTN_EM_STUANSWER            1009
#define IDC_BTN_EM_STDANSWER            1010
#define IDC_EDIT1                       1010
#define IDC_BTN_EM_CLOSE                1011
#define IDC_STATIC_BK                   1011
#define IDC_COMBO1                      1012
#define IDC_TREE_EM_EXAM_QUESTION       1012
#define IDC_BTN_EM_RENAME               1012
#define IDC_CMB_QVAULT                  1012
#define IDC_CMB_GENDER                  1012
#define IDC_BTN_EM_EXAM_PREV            1013
#define IDC_BTN_EM_EXAM_BEGIN           1014
#define IDC_BTN_EM_EXAM_NEXT            1015
#define IDC_BTN_EM_EXAM_STOP            1016
#define IDC_BTN_EM_EXAM_ABORT           1017
#define IDC_BTN_EM_EXAM_STUANSWER       1018
#define IDC_BTN_EM_EXAM_STDANSWER       1019
#define IDC_BTN_EM_EXAM_CLOSE           1020
#define IDC_EXAM_RICHEDIT_ANSWER        1021
#define IDC_EXAM_RICHEDIT_QUESTION      1022
#define IDC_STATIC_AREA                 1023
#define IDC_STATIC_QUESTION             1024
#define IDC_STATIC_TEXT                 1025
#define IDC_RADIO_A                     1026
#define IDC_RADIO_C                     1027
#define IDC_STATIC_BK_MEDIA             1027
#define IDC_RADIO_B                     1028
#define IDC_RADIO4                      1029
#define IDC_RADIO_D                     1029
#define IDC_GRID_CREATE                 1030
#define IDC_RADIO_E                     1030
#define IDC_MEDIA_CREATE                1031
#define IDC_RADIO_F                     1031
#define IDC_BUTTON1                     1035
#define IDC_BUTTON_PLAY                 1035
#define IDC_BTN_ADD                     1035
#define IDC_STATIC_BK_MEDIAPLAY         1036
#define IDC_BTN_UPDATE                  1036
#define IDC_STATIC_NO                   1037
#define IDC_BTN_DEL                     1037
#define IDC_LIST1                       1038
#define IDC_LIST_LOG                    1038
#define IDC_LIST_FACTORS                1038
#define IDC_EDIT_MARK                   1039
#define IDC_EDIT_NAME                   1040
#define IDC_CMB_QTYPE                   1041
#define IDC_EDIT_QNUM                   1042
#define IDC_LIST_CON                    1043
#define IDC_BTN_OK                      1044
#define IDC_BTN_CANCEL                  1045
#define IDC_EDIT_QMARK                  1046
#define IDC_EDIT_ID                     1046
#define IDC_EDIT_LEVEL                  1047
#define IDC_EDIT_DEP                    1048
#define IDC_EDIT_PHONE                  1049
#define IDC_EDIT_EMAIL                  1050
#define IDC_LIST_EXAM                   1050
#define IDC_EDIT_QQ                     1051
#define IDC_LIST_EXERCISE               1051
#define IDC_EDIT_AGE                    1052
#define IDP_AFXBARRES_IMAGE_IS_REQUIRED 16001
#define IDP_AFXBARRES_TEXT_IS_REQUIRED  16002
#define IDC_AFXBARRES_CLEAR             16003
#define IDP_AFXBARRES_CANNT_CREATE_IMAGE 16003
#define IDC_AFXBARRES_COPY              16004
#define IDP_AFXBARRES_CANT_PASTE_BITMAP 16004
#define IDC_AFXBARRES_PASTE             16005
#define IDS_AFXBARRES_WRONG_IMAGE_SIZE  16005
#define IDS_AFXBARRES_MENU_BAR_TITLE    16006
#define IDS_AFXBARRES_NO_MENUBAR        16007
#define IDP_AFXBARRES_INTERLAL_ERROR    16008
#define IDP_AFXBARRES_UNASSIGNED        16009
#define IDP_AFXBARRES_CANT_COPY_BITMAP  16010
#define IDS_AFXBARRES_HIDE_BAR          16011
#define IDS_AFXBARRES_EXPAND_BAR        16012
#define IDS_AFXBARRES_CONTRACT_BAR      16013
#define IDS_AFXBARRES_NEW_MENU          16014
#define IDS_AFXBARRES_FILE              16015
#define IDS_AFXBARRES_FOLDER            16016
#define IDS_AFXBARRES_NEW               16017
#define IDS_AFXBARRES_EXISTING          16018
#define IDS_AFXBARRES_RECENT            16019
#define IDS_AFXBARRES_DELETE            16020
#define IDS_AFXBARRES_MOVEUP            16021
#define IDS_AFXBARRES_MOVEDN            16022
#define IDS_AFXBARRES_CMD_FILTER        16023
#define IDS_AFXBARRES_TOO_MANY_TOOLS_FMT 16024
#define IDS_AFXBARRES_EXPAND_FMT        16025
#define IDS_AFXBARRES_MORE_BUTTONS      16026
#define IDS_AFXBARRES_NEW_FILE          16027
#define IDS_AFX_TEAR_OFF                16028
#define IDS_AFXBARRES_COMMAND           16029
#define IDS_AFXBARRES_KEYS              16030
#define IDS_AFXBARRES_DESCRIPTION       16031
#define IDS_AFXBARRES_CLOSEBAR          16032
#define IDS_AFXBARRES_AUTOHIDEBAR       16033
#define IDP_AFXBARRES_SCROLL_LEFT       16034
#define IDP_AFXBARRES_SCROLL_RIGHT      16035
#define IDS_AFXBARRES_AUTOHIDE_ALL      16036
#define IDR_AFXBARRES_POPUP_AFXTOOL_BAR 16102
#define IDS_AFXBARRES_PROPSHT_CAPTION   16103
#define IDD_AFXBARRES_PROPPAGE1         16104
#define IDS_AFXBARRES_UNTITLED_TOOLBAR  16104
#define IDD_AFXBARRES_PROPPAGE2         16105
#define IDS_AFXBARRES_CLOSE             16105
#define IDS_AFXBARRES_DEFUALT_MENU      16106
#define IDS_AFXBARRES_DEFAULT_MENU_DESCR 16107
#define IDS_AFXBARRES_NO_CONTEXT        16108
#define IDS_AFXBARRES_DELETE_TOOLBAR_FMT 16109
#define IDS_AFXBARRES_ALL_COMMANDS      16110
#define IDS_AFXBARRES_RESET_TOOLBAR_FMT 16111
#define IDS_AFXBARRES_RESET_ALL_TOOLBARS 16112
#define IDS_AFXBARRES_RESET_MENU_FMT    16113
#define IDS_AFXBARRES_DEFAULT_VIEW      16114
#define IDS_AFXBARRES_RESET_KEYBOARD    16115
#define IDB_AFXBARRES_MENU_IMAGES       16129
#define IDD_AFXBARRES_TOOLBAR_NAME      16130
#define IDB_AFXBARRES_HELP              16131
#define IDD_AFXBARRES_BUTTON_PROPS      16132
#define IDC_AFXBARRES_DELETE            16133
#define IDD_AFXBARRES_IMAGE_EDITOR      16133
#define IDD_AFXBARRES_PROPPAGE3         16134
#define IDD_AFXBARRES_PROPPAGE4         16135
#define IDD_AFXBARRES_PROPPAGE5         16136
#define IDD_AFXBARRES_PROPPAGE6         16137
#define IDR_AFXRES_PALETTE              16138
#define IDR_AFXRES_PALETTE32            16139
#define IDC_AFXBARRES_RECT              16140
#define IDC_AFXBARRES_ELLIPSE           16141
#define IDC_AFXBARRES_FILL              16142
#define IDC_AFXBARRES_LINE              16143
#define IDC_AFXBARRES_PEN               16144
#define IDC_AFXBARRES_COLOR             16145
#define IDC_AFXBARRES_MOVE              16146
#define IDS_AFXBARRES_TOO_MANY_TOOLBARS_FMT 16243
#define IDS_AFXBARRES_RESET_USAGE_WARNING 16244
#define IDS_AFXBARRES_RESET_TOOLBAR     16300
#define IDC_AFXBARRES_BUTTON_TEXT       16500
#define IDC_AFXBARRES_BUTTONS_LIST      16504
#define IDC_AFXBARRES_IMAGE             16505
#define IDC_AFXBARRES_TEXT              16506
#define IDC_AFXBARRES_MENU_DESCRIPTION  16506
#define IDC_AFXBARRES_IMAGE_TEXT        16507
#define IDC_AFXBARRES_TEMPL_ICON        16507
#define IDC_AFXBARRES_IMAGE_LIST        16508
#define IDC_AFXBARRES_CONTEXT_MENU_CAPTION 16508
#define IDC_AFXBARRES_ADD_IMAGE         16509
#define IDC_AFXBARRES_EDIT_IMAGE        16510
#define IDC_AFXBARRES_DRAW_AREA         16513
#define IDC_AFXBARRES_COMMAND_DESCRIPTION 16514
#define IDC_AFXBARRES_COLORS            16516
#define IDC_AFXBARRES_TOOLBAR_NAME      16516
#define IDC_AFXBARRES_PREVIEW_AREA      16519
#define IDC_AFXBARRES_CONTEXT_HINT      16519
#define IDC_AFXBARRES_CONTEXT_FRAME     16520
#define IDC_AFXBARRES_VIEW_ICON         16526
#define IDC_AFXBARRES_ASSIGNED_TO       16527
#define IDC_AFXBARRES_ASSIGNED_TO_TITLE 16528
#define IDC_AFXBARRES_USER_IMAGE        16529
#define IDC_AFXBARRES_DEFAULT_IMAGE     16530
#define IDC_AFXBARRES_DEFAULT_IMAGE_AREA 16531
#define IDC_AFXBARRES_PALETTE           16533
#define IDC_AFX_RU_MENUS_TITLE          16538
#define IDC_AFX_RU_MENUS_LINE           16539
#define IDC_AFXBARRES_MENU_ANIMATION_LABEL 16543
#define IDC_AFXBARRES_CATEGORY          16601
#define IDC_AFXBARRES_USER_TOOLS        16602
#define IDC_AFXBARRES_BUTTON_DESCR      16603
#define IDC_AFXBARRES_TOOLBAR_LIST      16611
#define IDC_AFXBARRES_TEXT_LABELS       16612
#define IDC_AFXBARRES_RESET             16613
#define IDC_AFXBARRES_RESET_ALL         16614
#define IDC_AFXBARRES_NEW_TOOLBAR       16615
#define IDC_AFXBARRES_RENAME_TOOLBAR    16616
#define IDC_AFXBARRES_DELETE_TOOLBAR    16617
#define IDC_AFXBARRES_MENU_LIST         16621
#define IDC_AFXBARRES_CONTEXT_MENU_LIST 16622
#define IDC_AFXBARRES_RESET_MENU        16623
#define IDC_AFXBARRES_RESET_FRAME_MENU  16624
#define IDC_AFXBARRES_MENU_ANIMATION    16625
#define IDC_AFXBARRES_MENU_SHADOWS      16626
#define IDC_AFXBARRES_LIST_VIEWS        16631
#define IDC_AFXBARRES_NO_DBLCLIICK      16632
#define IDC_AFXBARRES_USE_DBLCLIICK     16633
#define IDC_AFXBARRES_LIST_OF_COMMANDS  16634
#define IDC_AFXBARRES_COMMANDS_LIST     16641
#define IDC_AFXBARRES_VIEW_TYPE         16642
#define IDC_AFXBARRES_CURRENT_KEYS_LIST 16643
#define IDC_AFXBARRES_NEW_SHORTCUT_KEY  16644
#define IDC_AFXBARRES_ASSIGN            16645
#define IDC_AFXBARRES_REMOVE            16646
#define IDC_AFXBARRES_RESET_SHORTCUTS   16647
#define IDC_AFXBARRES_SHOW_TOOLTIPS     16651
#define IDC_AFXBARRES_SHOW_TOOLTIPS_WITH_KEYS 16652
#define IDC_AFXBARRES_LARGE_ICONS       16653
#define IDC_AFXBARRES_SHOW_RECENTLY_USED_MENUS 16655
#define IDC_AFXBARRES_SHOW_MENUS_DELAY  16656
#define IDC_AFXBARRES_RESET_USAGE_DATA  16657
#define IDD_AFXBAR_RES_PRINT_PREVIEW    16658
#define IDC_AFXBARRES_COLOURPLACEHOLDER 16662
#define ID_AFX_TOOL_FILL                16901
#define ID_AFX_TOOL_PEN                 16902
#define ID_AFX_TOOL_PICK                16903
#define ID_AFX_TOOL_LINE                16904
#define ID_AFX_TOOL_RECT                16905
#define ID_AFX_TOOL_ELLIPSE             16906
#define ID_AFX_TOOL_COPY                16907
#define ID_AFX_TOOL_PASTE               16908
#define ID_AFX_TOOL_CLEAR               16909
#define ID_AFXBARRES_TOOLBAR_RESET      16910
#define ID_AFXBARRES_COPY_IMAGE         16911
#define ID_AFXBARRES_TOOLBAR_DELETE     16912
#define ID_AFXBARRES_TOOLBAR_APPEARANCE 16913
#define ID_AFXBARRES_TOOLBAR_IMAGE      16914
#define ID_AFXBARRES_TOOLBAR_TEXT       16915
#define ID_AFXBARRES_TOOLBAR_IMAGE_AND_TEXT 16916
#define ID_AFXBARRES_TOOLBAR_START_GROUP 16917
#define ID_AFXBARRES_TOOLBAR_NEW_MENU   16918
#define IDC_AFXBARRES_HAND              16919
#define IDC_AFXBARRES_ACTIVATE          16920
#define IDC_AFXBARRES_SAVE              16921
#define IDD_AFXBARRES_COMMANDS_LIST     16921
#define IDC_AFXBARRES_CLOSE             16922
#define IDD_AFXBARRES_COMMAND           16922
#define IDC_AFXBARRES_LIST              16923
#define IDD_AFXBARRES_BROWSE_COMMAND    16923
#define IDC_AFXBARRES_TILEHORZ          16924
#define IDD_AFXBARRES_ARGUMENTS         16924
#define IDC_AFXBARRES_MINIMIZE          16925
#define IDD_AFXBARRES_INITIAL_DIRECTORY 16925
#define IDC_AFXBARRES_CASCADE           16926
#define IDD_AFXBARRES_WINDOWS_DLG       16927
#define IDC_AFXBARRES_TILEVERT          16928
#define IDD_AFXBARRES_PROPPAGE7         16928
#define IDB_AFXBARRES_NEW               16929
#define IDB_AFXBARRES_DELETE            16930
#define IDB_AFXBARRES_UP                16931
#define IDI_AFXRES_TOOL                 16931
#define IDB_AFXBARRES_DOWN              16932
#define IDR_AFXRES_PRINT_PREVIEW32      16957
#define ID_AFXRES_TWO_PAGES_DUMMY       16959
#define IDR_AFXRES_PRINT_PREVIEW        16960
#define IDD_AFXBARRES_COLOR_DLG         16961
#define IDD_AFXBARRES_COLOR_PAGE_ONE    16962
#define IDD_AFXBARRES_COLORPAGE_TWO     16963
#define IDC_AFXBARRES_R                 16964
#define IDC_AFXBARRES_G                 16965
#define IDC_AFXBARRES_B                 16966
#define IDC_AFXBARRES_L                 16967
#define IDC_AFXBARRES_S                 16968
#define IDC_AFXBARRES_H                 16969
#define IDC_AFXBARRES_STATICPLACEHOLDER 16970
#define IDC_AFXBARRES_GREYSCALEPLACEHOLDER 16972
#define IDC_AFXBARRES_LUMINANCEPLACEHOLDER 16973
#define IDC_AFXBARRES_HEXPLACEHOLDER    16974
#define IDC_AFXBARRES_SPIN1             16976
#define IDC_AFXBARRES_SPIN2             16977
#define IDC_AFXBARRES_SPIN3             16978
#define IDC_AFXBARRES_SPIN4             16979
#define IDC_AFXBARRES_SPIN5             16980
#define IDC_AFXBARRES_SPIN6             16981
#define IDD_AFXBARRES_KEYMAP            16982
#define IDD_AFXBARRES_MENU_ARGUMENTS    16989
#define IDC_AFXBARRES_PRINT_KEYMAP      16990
#define IDC_AFXBARRES_COPY_KEYMAP       16991
#define IDC_AFXBARRES_KEYLIST           16992
#define IDB_AFXBARRES_PRINT             16993
#define IDB_AFXBARRES_COPY              16994
#define IDI_AFXBARRES_HELP              16995
#define IDC_AFXBARRES_ACCEL_LABEL       16996
#define IDD_AFXBARRES_MENU_INITIAL_DIRECTORY 16997
#define IDB_AFXBARRES_FONT              17000
#define IDD_AFXBARRES_OUTLOOKBAR_OPTIONS 17004
#define IDC_AFXBARRES_APPLY             17008
#define ID_AFXBARRES_TOOLBAR_RESET_PROMT 17016
#define IDS_AFXBARRES_TOOLBAR_OPTIONS   17017
#define IDS_AFXBARRES_ADD_REMOVE_BTNS   17018
#define IDB_AFXBARRES_TASKPANE          17019
#define IDS_AFXBARRES_TASKPANE          17019
#define ID_AFXBARRES_TASKPANE_BACK      17020
#define ID_AFXBARRES_TASKPANE_FORWARD   17021
#define ID_AFXBARRES_TASKPANE_HOME      17022
#define ID_AFXBARRES_TASKPANE_CLOSE     17023
#define ID_AFXBARRES_TASKPANE_OTHER     17024
#define IDS_AFXBARRES_FULLSCREEN_CLOSE  17025
#define IDC_AFXBARRES_MOVEUP            17025
#define IDS_AFXBARRES_FULLSCREEN        17026
#define IDC_AFXBARRES_MOVEDOWN          17026
#define IDS_AFXBARRES_SHOWONEROW        17027
#define IDS_AFXBARRES_SHOWTWOROWS       17028
#define IDS_AFXBARRES_SHOW_MORE_BUTTONS 17029
#define IDS_AFXBARRES_SHOW_FEWER_BUTTONS 17030
#define IDS_AFXBARRES_NAV_PANE_OPTIONS  17031
#define IDB_AFXBARRES_BROWSE            17032
#define IDB_AFXBARRES_SD_TOP            17033
#define IDB_AFXBARRES_SD_BOTTOM         17034
#define IDB_AFXBARRES_SD_LEFT           17035
#define IDB_AFXBARRES_SD_MIDDLE         17036
#define IDB_AFXBARRES_SD_RIGHT          17037
#define IDS_AFXBARRES_MENU              17038
#define IDS_AFXBARRES_FLOATING          17039
#define IDS_AFXBARRES_DOCKING           17040
#define IDS_AFXBARRES_AUTOHIDE          17041
#define IDS_AFXBARRES_HIDE              17042
#define IDS_AFXBARRES_OPENED_DOCS       17043
#define IDB_AFXBARRES_SD_CENTER         17044
#define IDC_AFXBARRES_COLOR_SELECT      17045
#define IDB_AFXBARRES_COLOR_PICKER      17046
#define IDC_AFXBARRES_MOVE_TAB          17047
#define IDC_AFXBARRES_NO_MOVE_TAB       17048
#define IDB_AFXBARRES_BROWSE32          17049
#define IDB_AFXBARRES_PRINT32           17050
#define IDB_AFXBARRES_COPY32            17051
#define IDB_AFXBARRES_TASKPANE32        17052
#define IDB_AFXBARRES_NEW32             17053
#define IDB_AFXBARRES_DELETE32          17054
#define IDB_AFXBARRES_UP32              17055
#define IDI_AFXRES_TOOL32               17056
#define IDB_AFXBARRES_DOWN32            17057
#define IDD_AFXBARRES_POPUP_DLG         17058
#define IDB_AFXBARRES_HELP32            17067
#define IDD_AFXBARRES_PROPPAGE8         17074
#define IDS_AFXBARRES_ADD               17075
#define IDD_AFXBARRES_RIBBON_KEYBOARD_DLG 17076
#define IDC_AFXBARRES_QAT_COMMANDS_LIST 17077
#define IDC_AFXBARRES_QAT_ON_BOTTOM     17078
#define IDC_AFXBARRES_KEYBOARD          17079
#define IDB_AFXBARRES_MENU_IMAGES24     17080
#define IDS_AFXBARRES_PLACE_QAT_BELOW_RIBBON 17081
#define IDS_AFXBARRES_PLACE_QAT_ABOVE_RIBBON 17082
#define IDS_AFXBARRES_ADD_TO_QAT        17083
#define IDS_AFXBARRES_REMOVE_FROM_QAT   17084
#define IDS_AFXBARRES_CUSTOMIZE_QAT     17085
#define IDS_AFXBARRES_MINIMIZE_RIBBON   17086
#define IDS_AFXBARRES_STATBAR_CUSTOMIZE 17087
#define IDS_AFXBARRES_TABBED            17088
#define IDB_AFXBARRES_RIBBON_PRINT_LARGE 17089
#define IDB_AFXBARRES_RIBBON_PRINT_SMALL 17090
#define IDS_AFXBARRES_PRINT_PREVIEW     17091
#define IDS_AFXBARRES_PRINT             17092
#define IDS_AFXBARRES_ZOOM              17093
#define IDS_AFXBARRES_PREVIEW           17094
#define IDS_AFXBARRES_QAT_SEPARATOR     17095
#define IDS_AFXBARRES_CUSTOMIZE_QAT_TOOLTIP 17096
#define IDS_AFXBARRES_MORE_COMMANDS     17097
#define IDS_AFXBARRES_PLACE_BELOW_RIBBON 17098
#define IDS_AFXBARRES_PLACE_ABOVE_RIBBON 17099
#define IDI_AFXRES_LINK                 17100
#define IDS_AFXBARRES_CANCEL            17101
#define IDS_AFXBARRES_UNDO_FMT          17102
#define IDS_AFXBARRES_UNDO_ONE          17103
#define IDI_AFXRES_COLORS               17105
#define IDS_AFXBARRES_MORE              17107
#define IDS_AFXBARRES_GALLERY_ROW1_FMT  17108
#define IDS_AFXBARRES_GALLERY_ROW2_FMT  17109
#define IDD_YDMAIN_BLEW_VIEW            30010
#define IDD_DLG_PERSIONINFO_HISTORY     30011
#define ID_BLEW_PROPERTY_SAVE           30155
#define ID_BLEW_PROPERTY_UPDATE         30156
#define ID_BLEW_PROPERTY_CANCEL         30157
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_EM_NEW_EXERCISE              32778
#define ID_ID_EM_LOAD_EXERCISE          32779
#define ID_EM_NEW_EXAM                  32780
#define ID_EM_NEW_WORKSPACE             32781
#define ID_EM_NEW_EXAMTIME              32782
#define ID_ID_EM_EXERCISE_CFG           32783
#define ID_ID_EM_EXAM_CFG               32784
#define ID_EM_SET_WORKSPACE             32785
#define ID_EM_SET_EXAMTIME              32786
#define ID_ID_EM_SET_EXERCISE_CFG       32787
#define ID_ID_EM_SET_EXAM_CFG           32788
#define IID_EM_LOAD_EXERCISE            32789
#define ID_EM_LOAD_EXERCISE             32790
#define ID_EM_SET_EXERCISE_CFG          32791
#define ID_EM_SET_EXAM_CFG              32792
#define ID_32793                        32793
#define ID_EM_LOADVAULT                 32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        343
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
