--题库大类
CREATE TABLE "QVAULTCLASSIFICATION" 
 (	
"OBJID" NUMBER(38,0) NOT NULL ENABLE, 
"NAME" NVARCHAR2(128 ) NOT NULL ENABLE, 
"CREATOR" NVARCHAR2(128), 
"CREATEDATE" DATE NOT NULL ENABLE, 
"DESCRIPTION" NVARCHAR2(256), 
 CONSTRAINT "QVAULTCLASSIFICATION_PK" PRIMARY KEY ("OBJID")
  );
create sequence S_QVAULTCLASSIFICATION
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--题库大类层次关系
CREATE TABLE "QVCLASSIFICATIONHIERARCHY" 
 (	
"OBJID" NUMBER(38,0) NOT NULL ENABLE, 
"ID_A" NUMBER(38,0) NOT NULL ENABLE, 
"ID_B" NUMBER(38,0) NOT NULL ENABLE, 
 CONSTRAINT "QVAULTCLASSIFICATIONHIERA_PK" PRIMARY KEY ("OBJID")
 );

create sequence S_QVCLASSIFICATIONHIERARCHY
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;


--题库
CREATE TABLE "QUESTIONVAULT" 
 (
"OBJID" NUMBER NOT NULL ENABLE, 
"NAME" NVARCHAR2(128) NOT NULL ENABLE, 
"CREATOR" NVARCHAR2(128), 
"CREATEDATE" DATE, 
"DESCRIPTION" NVARCHAR2(256), 
CONSTRAINT "QUESTIONVAULT_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_QUESTIONVAULT
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--题库大类与题库关系
CREATE TABLE "QCLASSIFICATIONQVAULT" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "QCLASSIFICATIONQVAULT_PK" PRIMARY KEY ("OBJID")
  );
  
create sequence S_QCLASSIFICATIONQVAULT
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;


--题型
  CREATE TABLE "QUESTIONTYPE" 
 (	
 "OBJID" NUMBER NOT NULL ENABLE, 
"NAME" NVARCHAR2(128) NOT NULL ENABLE, 
"CREATOR" NVARCHAR2(128) NOT NULL ENABLE, 
"CREATEDATE" DATE NOT NULL ENABLE, 
"DESCRIPTION" NVARCHAR2(256), 
"TYPE" NUMBER, 
 CONSTRAINT "QUESTIONTYPE_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_QUESTIONTYPE
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;
 
--题库与题型关系
 CREATE TABLE "QVAULTQTYPE" 
   (	
  "OBJID" NUMBER NOT NULL ENABLE, 
	"ID_A" NUMBER NOT NULL ENABLE, 
	"ID_B" NUMBER NOT NULL ENABLE, 
  CONSTRAINT "QVAULTQTYPE_PK" PRIMARY KEY ("OBJID")
   );
   
create sequence S_QVAULTQTYPE
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;



--知识点
CREATE TABLE "KNOWLEDGEPOINT" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"NAME" NVARCHAR2(128) NOT NULL ENABLE, 
"CODE" NVARCHAR2(128), 
"CREATOR" NVARCHAR2(128) NOT NULL ENABLE, 
"CREATEDATE" DATE NOT NULL ENABLE, 
"DESCRIPTION" NVARCHAR2(256), 
 CONSTRAINT "KNOWLEDGEPOINT_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_KNOWLEDGEPOINT
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--题库与知识点
CREATE TABLE "QVAULTKPOINT" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "QVAULTKPOINT_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_QVAULTKPOINT
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;


--选择类型题目
CREATE TABLE "CHOICEQUESTION" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"CODE" NVARCHAR2(128), 
"TITLE" NVARCHAR2(1024), 
"CHOICE" NVARCHAR2(1024), 
"TYPEID" NUMBER NOT NULL ENABLE, 
"ANSWER" NVARCHAR2(1024) NOT NULL ENABLE, 
"HARDLEVEL" NUMBER DEFAULT 1 NOT NULL ENABLE, 
"USEDCOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
"CREATOR" NVARCHAR2(128) NOT NULL ENABLE, 
"ANSWERDESC" NVARCHAR2(512) NOT NULL ENABLE, 
"CREATEDATE" DATE NOT NULL ENABLE, 
 CONSTRAINT "CHOICEQUESTION_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_CHOICEQUESTION
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--带有阅读资料题
  CREATE TABLE "ARTICLEQUESTION" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"ARTICLE" CLOB NOT NULL ENABLE, 
"TYPEID" NUMBER NOT NULL ENABLE, 
"HARDLEVEL" NUMBER DEFAULT 0 NOT NULL ENABLE, 
"USEDCOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
"CREATOR" NVARCHAR2(128) NOT NULL ENABLE, 
"CREATEDATE" DATE NOT NULL ENABLE, 
 CONSTRAINT "ARTICLEQUESTION_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_ARTICLEQUESTION
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--题库与试题的关系
 CREATE TABLE "QVAULTQUESTION" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
"ID_TYPE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
 CONSTRAINT "QVAULTQUESTION_PK" PRIMARY KEY ("OBJID")
  );

create sequence S_QVAULTQUESTION
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;


--文摘与题目关系
CREATE TABLE "ARTICLEQCHOICEQ" 
(	
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
CONSTRAINT "ARTICLEQCHOICEQ_PK" PRIMARY KEY ("OBJID")
);

create sequence S_ARTICLEQCHOICEQ
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;


--问题与知识点关系
CREATE TABLE "QUESTIONKPOINT" 
 (
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
"ID_TYPE" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "QUESTIONKPOINT_PK" PRIMARY KEY ("OBJID")
 );

create sequence S_QUESTIONKPOINT
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;



--试卷夹
CREATE TABLE "PAPERFOLDER" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"NAME" NVARCHAR2(128), 
"CREATOR" NVARCHAR2(128), 
"CREATEDATE" DATE, 
"DESCRIPTION" NVARCHAR2(256), 
 CONSTRAINT "PAPERFOLDER_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_PAPERFOLDER
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--试卷夹层次关系
CREATE TABLE "PFOLDERHIERARCHY" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "PFOLDERHIERARCHY_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_PFOLDERHIERARCHY
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

 
 --试卷
  CREATE TABLE "PAPER" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"NAME" NVARCHAR2(128) NOT NULL ENABLE, 
"CREATOR" NVARCHAR2(128), 
"CREATEDATE" DATE , 
"CODE" NVARCHAR2(128), 
"GUIDNAME" NVARCHAR2(128) , 
"DESCRIPTION" NVARCHAR2(256), 

"BEGIN1" NUMBER , 
"END1" NUMBER , 
"CHOICECOUNT1" NUMBER , 
"MULTIFLAG1" NUMBER , 

"BEGIN2" NUMBER , 
"END2" NUMBER , 
"CHOICECOUNT2" NUMBER , 
"MULTIFLAG2" NUMBER , 

"BEGIN3" NUMBER , 
"END3" NUMBER , 
"CHOICECOUNT3" NUMBER , 
"MULTIFLAG3" NUMBER , 
 CONSTRAINT "PAPER_PK" PRIMARY KEY ("OBJID")
 );

create sequence S_PAPER
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--文件夹与试卷关系
CREATE TABLE "PFOLDERPAPER" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "PFOLDERHIERARCHY_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_PFOLDERPAPER
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--多媒体表
CREATE TABLE "MEDIA" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"NAME" NVARCHAR2(128) NOT NULL ENABLE, 
"TYPE" NUMBER NOT NULL ENABLE, 
"USEFOR" NUMBER NOT NULL ENABLE, 
"CREATOR" NVARCHAR2(128) NOT NULL ENABLE, 
"CREATEDATE" DATE NOT NULL ENABLE, 
"GUIDNAME" NVARCHAR2(128), 
 CONSTRAINT "MEDIA_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_MEDIA
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

--题目和多媒体
  CREATE TABLE "QUESTIONMEDIA" 
 (	
"OBJID" NUMBER NOT NULL ENABLE, 
"ID_A" NUMBER NOT NULL ENABLE, 
"ID_B" NUMBER NOT NULL ENABLE, 
"ID_TYPE" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "QUESTIONMEDIA_PK" PRIMARY KEY ("OBJID")
 );
 
create sequence S_QUESTIONMEDIA
increment by 1 
start with 1
nomaxvalue
order
nocycle
nocache;

CREATE TABLE "YDFTP" 
 (
"OBJID" NUMBER NOT NULL ENABLE, 
"ADDR" NVARCHAR2(255) NOT NULL ENABLE, 
"USERNAME" NVARCHAR2(128) NOT NULL ENABLE,
"PWD" NVARCHAR2(128),
CONSTRAINT "YDFTP_PK" PRIMARY KEY ("OBJID")
 );

--触发器
create or replace trigger tg_QVCLASSHY
BEFORE INSERT ON QVCLASSIFICATIONHIERARCHY
FOR EACH ROW
BEGIN
  SELECT S_QVCLASSIFICATIONHIERARCHY.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/

create or replace trigger tg_QCFQV
BEFORE INSERT ON QCLASSIFICATIONQVAULT
FOR EACH ROW
BEGIN
  SELECT S_QCLASSIFICATIONQVAULT.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/

create or replace trigger tg_QVAULTQUESTION
BEFORE INSERT ON QVAULTQUESTION
FOR EACH ROW
BEGIN
  SELECT S_QVAULTQUESTION.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/

create or replace trigger tg_QVAULTQTYPE
BEFORE INSERT ON QVAULTQTYPE
FOR EACH ROW
BEGIN
  SELECT S_QVAULTQTYPE.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/
create or replace trigger tg_QUESTIONMEDIA
BEFORE INSERT ON QUESTIONMEDIA
FOR EACH ROW
BEGIN
  SELECT S_QUESTIONMEDIA.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/
create or replace trigger tg_PFHY
BEFORE INSERT ON PFOLDERHIERARCHY
FOR EACH ROW
BEGIN
  SELECT S_PFOLDERHIERARCHY.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/
create or replace trigger tg_QUESTIONKPOINT
BEFORE INSERT ON QUESTIONKPOINT
FOR EACH ROW
BEGIN
  SELECT S_QUESTIONKPOINT.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/

create or replace trigger tg_ARTICLEQCHOICEQ
BEFORE INSERT ON ARTICLEQCHOICEQ
FOR EACH ROW
BEGIN
  SELECT S_ARTICLEQCHOICEQ.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/
create or replace trigger tg_QVAULTKPOINT
BEFORE INSERT ON QVAULTKPOINT
FOR EACH ROW
BEGIN
  SELECT S_QVAULTKPOINT.NEXTVAL INTO :NEW.OBJID FROM dual;
END;
/
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (1,1, '写作题', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '写作题');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (2,3, '深度阅读', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '深度阅读');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (3,2, '听力题', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '听力题');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (4,4,'完型填空', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'),'完型填空');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (5,5, '翻译题', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '翻译题');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (6,6, '词汇与语法', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '词汇与语法');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (7,7, '快速阅读题', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '快速阅读题');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (8,8, '阅读选词填空', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '阅读选词填空');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (9,9, '听力填空', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '听力填空');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (10,10, '短句听力', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '短句听力');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (11,11, '长句听力', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '长句听力');
INSERT INTO QUESTIONTYPE (OBJID,TYPE, NAME, CREATOR, CREATEDATE, DESCRIPTION) VALUES (12,12, '改错', '南京我佰分',to_date('2010-05-01','yyyy-mm-dd'), '改错');


