//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by YDVaultMain.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_YDVAULTMAIN_PAPER_MANAGEMENT 101
#define IDS_YDQVAULT_TREE_ROOT          102
#define IDS_YDVAULTMAIN_PAPERMGR_ROOT   103
#define IDS_YDVAULTMAIN_DELETE_INFO_FORMAT 104
#define IDS_YDVAULTMAIN_DELETEPF_WARNING 105
#define IDS_YDVAULTMAIN_EXAM            106
#define IDS_YDVAULTMAIN_EXAM_MANAGEM    107
#define IDS_YDVAULTMAIN_DATA_MAINTAIN   108
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_YDVaultMainTYPE             130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_PROPERTIES                   135
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_YDFORMVIEW                  310
#define IDD_DIALOG_QUESTION_TYPE        312
#define IDR_HTML_QUESTIONKNOWLEDGEFORMVIEW 313
#define IDR_MENU_QUESTION_VAULT_CLASSIFICATION 315
#define IDR_MENU_PFTREE_ROOT            317
#define IDR_MENU3                       318
#define IDR_MENU_PFTREE_PF              318
#define IDB_BITMAP_QUESTION_VAULT       319
#define IDR_MENU_QUESTION_VAULT         319
#define IDB_BITMAP_QUESTION_VAULT_CLASSIFICATION 320
#define IDD_DIALOG4                     322
#define IDB_BITMAP_QUESTION_TYPE        326
#define IDD_YDQUESTIONDLG               327
#define IDR_MENU1                       328
#define IDR_MENU_QUESTION_TYPE          328
#define IDR_MENU2                       343
#define IDD_DIALOG_QUESTION_DB          344
#define IDC_EDIT_NUMBER                 1001
#define IDC_DATETIMEPICKER_CREATEDATE   1002
#define IDC_EDIT_CQ_CHOICE              1003
#define IDC_DATETIMEPICKER_PFCREATEDATE 1007
#define IDC_EDIT_CQ_ANSWER2             1008
#define IDC_DATETIMEPICKER_CREATE       1012
#define IDC_EDIT_PFDate                 1012
#define IDC_BUTTON_ADD2                 1018
#define IDC_COMBO_CQ_TYPEID             1020
#define IDC_DATETIMEPICKER_CQ_CREATE    1023
#define IDC_COMBO_AQ_TYPEID             1025
#define IDC_DATETIMEPICKER_AQ_CREATE    1028
#define IDC_DATETIMEPICKER_QT_CREATEDATE 1031
#define IDC_TAB1                        1033
#define IDC_LIST2                       1035
#define IDC_TEXT3                       1038
#define IDC_BTN_GP_SAVE                 1039
#define IDC_LIST_ALL_KNOWLEDGE          1048
#define IDC_EDIT1                       1049
#define IDC_BUTTON_PREV_VIEW            1056
#define IDC_BUTTON_CQ_UPDATE            1056
#define IDC_BUTTON2                     1058
#define IDC_BUTTON_CQ_SAVE              1058
#define IDC_RICHEDIT_TITLE2             1058
#define IDC_BUTTON_CQ_CANCEL            1063
#define IDC_BUTTON_QL_QUERY_GOBEGIN     1079
#define IDC_BUTTON_CQ_MODIFY2           1082
#define IDC_BUTTON_NEW_QUESTION3        1085
#define IDC_BUTTON_CQ_ADDKP2            1088
#define IDC_BUTTON3                     1090
#define IDC_MSCHART1                    1094
#define IDC_BUTTON1                     1096
#define IDC_BUTTON4                     1097
#define IDC_QUESTION_TREE_VIEW          1098
#define IDC_PARPER_TREE_VIEW            1099
#define IDC_RICHEDIT21                  1100
#define ID                              1101
#define IDC_COMBO1                      1103
#define IDC_TREE                        1104
#define IDD_YDMAIN_BLEW_VIEW            30010
#define IDD_YDMAIN_DIALOG_QUESTION_VAULT1 30011
#define IDD_DIALOG_GENERATEPAPER1       30012
#define ID_BLEW_PROPERTY_SAVE           30155
#define ID_BLEW_PROPERTY_UPDATE         30156
#define ID_PROPERTY_CANCEL              30157
#define ID_BLEW_PROPERTY_CANCEL         30157
#define ID_32771                        32771
#define ID_QUESTION_VAULT_REFRESH       32772
#define ID_32773                        32773
#define ID_QUESTION_VAULT_EDIT          32774
#define ID_32775                        32775
#define ID_QUESTION_VAULT_NEW_QUESTION_VAULT 32776
#define ID_32777                        32777
#define ID_QUESTION_VAULT_DEL           32778
#define ID_YDMAIN_BLEW_VIEW             32779
#define ID_QUESTION_VAULT_NEW_QUESTION_VAULT_CLASSIFIACTION 32780
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_PFTREE_ROOT_REFRESH          32783
#define ID_MI_PFTREE_ROOT_NEWPF         32784
#define ID_MI_PFTREE_ROOT_REFRESH       32785
#define ID_32786                        32786
#define ID_32787                        32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_MI_P                         32790
#define ID_MI_PFTREE_PF_DELETE          32791
#define ID_MI_PFTREE_PF_EDIT            32792
#define ID_MI_PFTREE_PF_NEWSUBPF        32793
#define ID_MI_PFTREE_PF_REFRESH         32794
#define ID_32795                        32795
#define ID_QUESTION_NEW                 32796
#define ID_32797                        32797
#define ID_32798                        32798
#define ID_NEW_QUESTION                 32799
#define ID_SYS_NEWPERSON                32800
#define ID_SYSROLEMGR                   32801
#define ID_32802                        32802
#define ID_                             32803
#define ID_MI_MAKEPAPER                 32804
#define ID_VIEW_QUESTION_TREE           32805
#define ID_VIEW_PAPER_TREE              32806
#define ID_VIEW_EXAM_TREE               32807
#define ID_VIEW_DATAMAINTAIN_TREE       32808
#define ID_VIEW_DATAQUERY_TREE          32809
#define ID_32810                        32810
#define ID_32811                        32811
#define ID_VIEW_MSG_DLG                 32814
#define ID_VIEW_HANDLE_EXAM_TREE        32815
#define ID_SYS_USERMRG                  32816
#define ID_32817                        32817
#define ID_SYS_USER_MODIFY_PWD          32818
#define ID_SYS_RELOGIN                  32819
#define ID_SYS_LOAD_CFG                 32820
#define IDS_YDVAULTMAIN_QUESTION_MANAGEMENT 61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        345
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           328
#endif
#endif
