//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by YDUIExamDataMaintain.rc
//
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_CLASS_SET 217
#define IDD_YDUIEXAM_DATA_MAINTAIN_FORM_DEPARTMENT 257
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_DEPARTMENT 260
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_SUBJECT 279
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_PAPER 279
#define IDD_DIG_TEACHERDEV              295
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_TEACHERDEV 295
#define IDB_SHOWALL_DOWN                462
#define IDB_SHOWALL                     463
#define IDB_ADDDEPART_DOWN              498
#define IDB_ADDDEPART                   499
#define IDB_ADDCLASS_DOWN               500
#define IDB_ADDCLASS                    501
#define IDB_UPDATEDEPART_DOWN           502
#define IDB_UPDATEDEPART                503
#define IDB_UPDATECLASS_DOWN            504
#define IDB_UPDATECLASS                 505
#define IDB_DELETECLASS_DOWN            506
#define IDB_DELETECLASS                 507
#define IDB_DELETEDEPART_DOWN           510
#define IDB_DELETEDEPART                511
#define IDC_CLASSID                     1012
#define IDC_TEACHERID                   1012
#define IDC_HEAD                        1013
#define IDC_TEACHERNAME                 1013
#define IDC_TEL                         1014
#define IDC_TEACHERDEV                  1014
#define IDC_DEPART                      1015
#define IDC_DEPARTID                    1016
#define IDC_ADDCLASS                    1022
#define IDC_UPDATEDEPART                1023
#define IDC_UPDATECLASS                 1024
#define IDC_DISPLAY                     1027
#define IDC_DELETEDEPART                1028
#define IDC_DELETECLASS                 1029
#define IDC_CLASS                       1033
#define IDC_CLASSHEAD                   1034
#define IDC_CLASSHEADTEL                1035
#define IDC_EDIT_DEPARTMENT             1036
#define IDC_EDIT_QL_QUERY_TOTAL         1049
#define IDC_BTN_DM_QSTU_PREV            1075
#define IDC_BTN_DM_QSTU_NEXT            1076
#define IDC_BTN_DM_QSTU_END             1077
#define IDC_EDIT_QL_QUERY_PAGENUM       1078
#define IDC_BTN_DM_QSTU_BEGIN           1079
#define IDC_STATIC2                     1085
#define IDC_STATIC1                     1123
#define IDC_SUBJECT                     1172
#define IDC_SUBJECTID                   1173
#define IDC_DEPARTMENTLIST              1185
#define IDC_DEPARTMENT_LIST             1185
#define IDC_ADDDEPART                   1257
#define IDC_DATA_MAINTAIN_TREE          1258
#define IDC_CLASS_LIST                  17000
#define IDD_YDUIEXAM_DATA_MAINTAIN_STUDENT 17000
#define IDC_LIST_DM_STU                 17001
#define IDD_YDUIEXAM_DATA_MAINTAIN_FORM_SUBJECT 17001
#define IDC_CMB_DM_STUCONN_DEPT         17002
#define IDD_YDUIEXAM_DATA_MAINTAIN_FORM_TEA_DEVICE 17002
#define IDC_CMB_STUCONN_CLS             17003
#define IDD_YDUIEXAM_DATA_MAINTAIN_FORM_PAPER 17003
#define IDC_STATIC_DM_STUCON_GRID       17004
#define IDD_YDUIEXAM_DATA_MAINTAIN_FORM_EXAMADDR 17004
#define IDC_BTN_DM_STU_SEARCH           17005
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_SUBJ 17005
#define IDC_BTN_DM_STU_ADD              17006
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_EXAMADDR 17006
#define IDC_BTN_DM_STU_EDIT             17007
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_EDIT_ANSWER 17007
#define IDC_BTN_DM_STU_DEL              17008
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_EXAMADDR_STU 17008
#define IDC_LIST_DM_SUBJECT             17009
#define IDC_BTN_DM_PAPER_ANSWER_EDIT    17009
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_DEVICE 17009
#define BTN_DM_SUBJ_NEW                 17010
#define IDD_YDUIEXAM_DATA_MAINTAIN_FORM_DEVICE 17010
#define BTN_DM_SUBJ_EDIT                17011
#define BTN_DM_SUBJ_DEL                 17012
#define IDC_LIST_DM_TEA_DEVICE          17013
#define BTN_DM_SUBJ_EDITPAPER           17013
#define BTN_DM_TDEVICE_NEW              17014
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_SUBJECT_EDITPAPER 17014
#define BTN_DM_SUBJ_OUTPUT              17014
#define BTN_DM_TDEVICE_EDIT             17015
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_INPUT_STUDENT_PREVIEW 17015
#define BTN_DM_TDEVICE_DEL              17016
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_INPUT_STUDENT_PREVIEW1 17016
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_INPUT_DEVICE_PREVIEW 17016
#define IDC_STATIC_DM_PAPERCON_GRID     17017
#define BTN_DM_TDEVICE_DEL2             17017
#define BTN_DM_TDEVICE_OUTPUT           17017
#define IDC_BTN_DM_PAPER_SEARCH         17018
#define IDC_EDIT_QPAPER_QUERY_TOTAL     17019
#define IDC_EDIT_QPAPER_QUERY_PAGENUM   17020
#define IDC_BTN_DM_QPAPER_BEGIN         17021
#define IDC_BTN_DM_QPAPER_PREV          17022
#define IDC_BTN_DM_QPAPER_NEXT          17023
#define IDC_BTN_DM_QPAPER_END           17024
#define IDC_LIST_DM_PAPER               17025
#define IDC_BTN_DM_PAPER_ADD            17026
#define IDC_BTN_DM_PAPER_EDIT           17027
#define IDC_BTN_DM_PAPER_DEL            17028
#define IDC_STATIC_DM_EXAMADDRCON_GRID  17029
#define IDC_BTN_DM_PAPER_OUTPUT         17029
#define IDC_BTN_DM_EXAMADDR_SEARCH      17030
#define IDC_EDIT_QEXAMADDR_QUERY_TOTAL  17031
#define IDC_EDIT_QEXAMADDR_QUERY_PAGENUM 17032
#define IDC_LIST_DM_EXAMADDR            17033
#define IDC_BTN_DM_QEXAMADDR_BEGIN      17034
#define IDC_BTN_DM_QEXAMADDR_PREV       17035
#define IDC_BTN_DM_QEXAMADDR_NEXT       17036
#define IDC_BTN_DM_QEXAMADDR_END        17037
#define IDC_BTN_DM_EXAMADDR_ADD         17038
#define IDC_BTN_DM_EXAMADDR_EDIT        17039
#define IDC_BTN_DM_EXAMADDR_DEL         17040
#define IDC_BTN_DM_EXAMADDR_STU_EDIT    17041
#define IDC_DM_PAPER_CODE               17042
#define IDC_BTN_DM_EXAMADDR_OUTPUT      17042
#define IDC_DM_PAPER_NAME               17043
#define IDC_DM_EXAMADDR_CODE            17044
#define IDC_DM_EXAMADDR_ADDR            17045
#define IDC_BTN_DM_ANSWER_OK            17046
#define IDC_DM_ANSWER_EDIT_GRID         17047
#define IDC_LIST_DM_EXAMADDR_STUS       17051
#define IDC_LIST_DM_EXAMADDR_UNIT       17052
#define IDC_DM_EXAMADDR_DEPARTMENT      17057
#define IDC_DM_EXAMADDR_CLASS           17058
#define IDC_BTN_EXAMADDR_OK             17059
#define IDC_BTN_DM_STU_ADDQC            17060
#define IDC_BTN_DM_STU_DELQC            17061
#define IDC_EDIT_BEGIN1                 17061
#define IDC_BTN_DM_STU_CLEARQC          17062
#define IDC_EDIT_END1                   17062
#define IDC_EDIT_COUNT1                 17063
#define IDC_EDIT_BEGIN2                 17064
#define IDC_CMB_MULTI1                  17065
#define IDC_EDIT_END2                   17066
#define IDC_DM_DEVICE_CODE              17066
#define IDC_EDIT_COUNT2                 17067
#define IDC_DM_DEVICE_MAC               17067
#define IDC_CMB_MULTI2                  17068
#define IDC_STATIC_DM_DEVICECON_GRID    17068
#define IDC_EDIT_BEGIN3                 17069
#define IDC_LIST_DM_DEVICE              17069
#define IDC_EDIT_END3                   17070
#define IDC_BTN_DM_DEVICE_SEARCH        17070
#define IDC_EDIT_COUNT3                 17071
#define IDC_EDIT_QDEVICE_QUERY_TOTAL    17071
#define IDC_CMB_MULTI3                  17072
#define IDC_EDIT_QDEVICE_QUERY_PAGENUM  17072
#define IDC_BTN_DM_QDEVICE_BEGIN        17073
#define IDC_BTN_DM_QDEVICE_PREV         17074
#define IDC_BTN_DM_QDEVICE_NEXT         17075
#define IDC_BTN_DM_QDEVICE_END          17076
#define IDC_BTN_DM_DEVICE_ADD           17077
#define IDC_BTN_DM_DEVICE_EDIT          17078
#define IDC_BTN_DM_DEVICE_DEL           17079
#define IDC_BTN_DM_DEVICE_OUTPUT        17080
#define IDC_BTN_DM_DEVICE_INPUT         17081
#define IDC_EDIT_DM_EXAMADDR_EXAMID     17102
#define IDC_LIST_DM_EXAMADDR_DEVICE     17106
#define IDC_LIST_ALLPAPER               17108
#define IDC_LIST_SUBJECTPAPER           17109
#define IDC_BUTTON_ADD                  17110
#define IDC_BUTTON_DEL                  17111
#define IDC_BTN_DM_STU_OUTPUT           17112
#define IDC_BUTTON_INPUT                17113
#define IDC_STATIC_BK                   17114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        17016
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         17116
#define _APS_NEXT_SYMED_VALUE           17000
#endif
#endif
