//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HardCtrl.rc
//
#define IDC_PRINT                       2
#define IDC_DEL                         3
#define IDC_SPESTART                    4
#define IDD_ABOUTBOX                    100
#define IDD_HARDCTRL_FORM               101
#define IDD_FORM_GRAPH_DATA             101
#define IDD_FORM_EXAM                   101
#define IDD_FORM_MENU                   103
#define IDD_FORM_STUQUERY               104
#define IDD_CTRL_ACTION_DETAIL          116
#define IDD_CTRL_ACTION                 118
#define IDR_MAINFRAME                   128
#define IDR_HARDCTTYPE                  129
#define IDI_ICON1                       130
#define IDC_DE_ALL                      130
#define IDC_DRAGGING                    131
#define IDI_WEB                         131
#define IDI_CTRL                        132
#define IDC_SIP1                        132
#define IDD_DLG_MSG                     133
#define IDC_SIP2                        133
#define IDD_FORM_DOMAIN                 134
#define IDC_DIP1                        134
#define IDB_BITMAP_LIST                 135
#define IDC_HANDCUR                     135
#define IDC_DIP2                        135
#define IDC_SPORT1                      136
#define IDD_PROGRESS                    137
#define IDC_SPORT2                      137
#define IDC_DPORT1                      138
#define IDC_DPORT2                      139
#define IDC_CONNECT                     140
#define IDI_CONFIG                      141
#define IDD_FORM_IMPORT_IP              143
#define IDD_DLG_KIND                    144
#define IDD_FORM_CONFIG                 146
#define IDD_FORM_WEB_NAME               147
#define IDD_LEFT_AUDIT                  148
#define IDR_WEB                         149
#define IDD_LEFT_REPORT                 149
#define IDD_LEFT_MANAGE                 150
#define IDD_FORM_MAIN                   151
#define IDD_FORM_IPTABLES               152
#define IDD_DLG_IPTABLES                153
#define IDD_FORM_DATE_TIME              154
#define IDD_FROM_SUB                    155
#define IDD_DLG_GROUP                   156
#define IDD_DLG_COMPUTER                157
#define IDD_DLG_DATE                    158
#define IDD_DLG_TIME                    159
#define IDD_DLG_INPUT                   160
#define IDI_ICON16                      161
#define IDD_FORM_HARD                   161
#define IDD_DLG_LOG_IN                  162
#define IDD_FORM_GRAPH                  163
#define IDI_ICON19                      168
#define IDI_ICON20                      169
#define IDI_ICON12                      182
#define IDI_WEB_1                       195
#define IDI_CTRL_1                      196
#define IDI_CONFIG_1                    197
#define IDI_HELP                        198
#define IDC_CBRIDGE                     201
#define IDD_DLG_DEV                     201
#define IDD_DLG_ETH                     202
#define IDC_CNAT                        202
#define IDD_DLG_PACKET_QUERY            203
#define IDD_DLG_PACKET                  203
#define IDD_FORM_PACKET                 204
#define IDD_DLG_FLOOD                   205
#define IDD_DLG_SAFE                    206
#define IDD_FORM_SAFE                   206
#define IDC_TYPE                        206
#define IDC_CMB                         206
#define IDD_FORM_ACTION                 207
#define IDC_NAT                         207
#define IDC_CKB                         207
#define IDD_DLG_ACTION                  208
#define IDC_COUT                        208
#define IDC_BPS                         208
#define IDD_FORM_BPS                    209
#define IDC_CIN                         209
#define IDD_FORM_NAT                    210
#define IDC_LINE                        210
#define IDC_ETH                         210
#define IDC_CMIN_KB                     211
#define IDC_EXPORT                      211
#define IDD_DLG_DNS_DETAIL              211
#define IDC_IMPORT                      212
#define IDD_DLG_NAT_DETAIL              212
#define IDC_MIN_BPS                     212
#define IDD_DLG_ROUTE_DETAIL            213
#define IDC_PRIO                        213
#define IDC_REPORT                      214
#define IDD_DLG_DNS                     214
#define IDD_DLG_NAT                     215
#define IDC_MAX_BPS                     215
#define IDC_CTCP                        216
#define IDD_DLG_ROUTE                   216
#define IDC_CMAX_MB                     216
#define IDC_CMAX_KB                     217
#define IDC_CUDP                        217
#define IDD_DLG_CLASS                   217
#define IDD_DLG_CLASS_SET               217
#define IDC_DPORT                       218
#define IDD_DLG_CLASS_DETAIL            218
#define IDR_MAINFRAM                    218
#define IDD_DLG_MARK_DETAIL             219
#define IDC_IPDNS                       220
#define IDD_DLG_MARK                    220
#define IDC_GW                          221
#define IDC_ROUTE                       221
#define IDD_SETUSER                     221
#define IDD_GREATUSER                   222
#define IDD_INAPP                       224
#define IDD_DIALOG1                     225
#define IDD_DIALOG2                     226
#define IDD_SETPASS                     227
#define IDD_DLG_LOG                     231
#define IDB_BITMAP1                     234
#define IDR_TOOLBAR1                    239
#define IDD_DLG_IP                      241
#define IDD_DLG_CONFIG                  242
#define IDD_DLG_GRAPH                   243
#define IDD_DLG_GRAPH_DATA              244
#define IDD_FORM_GROUP_ACTION           245
#define IDD_DLG_ACTION_DETAIL           246
#define IDD_DLG_GRAPH_RANK              247
#define IDB_BITMAP2                     255
#define IDD_FORM_DEPARTMENT             257
#define IDD_FORM_ANSWER                 258
#define IDD_DLG_ANSWER                  259
#define IDD_DLG_DEPARTMENT              260
#define IDD_DLG_STUINFO                 262
#define IDD_FORM_RESULT                 266
#define IDD_FORM_EXMOPTION              267
#define IDC_NODRAGGING                  268
#define IDD_FORM_DEV                    270
#define IDD_DIG_DEV                     271
#define IDD_DIG_EXMOPTION               272
#define IDD_FORM_LINK                   273
#define IDD_DIG_PHOTO                   274
#define IDD_DIG_QUERY                   275
#define IDD_FORM_STUINFO                277
#define IDD_FORM_SUBJECT                278
#define IDD_DIG_SUBJECT                 279
#define IDD_FORM_EXAMADDR               281
#define IDD_DIG_EXAMADDR                282
#define IDD_DIG_STURESULT_QUERY         283
#define IDD_FORM_CLASSRESULT            285
#define IDD_DLG_CLASSRESULT             286
#define IDD_DIG_EXAM_STAT               287
#define IDD_DLG_LATE                    288
#define IDD_DIG_PERROLLING              289
#define IDD_DLG_SPEROLL                 290
#define IDD_DLG_LINKROLL                291
#define IDD_DIG_LINKROLLING             292
#define IDD_FORM_TEACHERDEV             293
#define IDD_DIG_SINGLEROLL              294
#define IDD_DIG_TEACHERDEV              295
#define IDD_DIG_RES_DETAIL              296
#define IDD_DIG_GRAPH                   298
#define IDD_DLG_PRE_ROLLING             301
#define IDD_FORM_STUINFO_SET            307
#define IDD_DLG_QUERY                   308
#define IDD_FORM_PAPER                  310
#define IDD_DLG_PAPER_SET               311
#define IDD_DLG_PAPER_QUERY             312
#define IDD_DLG_ANSWER_SET              314
#define IDD_DLG_EXAM_SET                315
#define IDD_FORM_PCOFF_ROLL             317
#define IDD_FORM_PCOFF_ROLLING          320
#define IDD_DLG_CLASS_QUERY             321
#define IDD_FORM_FM                     322
#define IDD_DLG_FM                      323
#define DLG_SYS_PREGOTO                 324
#define DLG_SYS_PREPARENT               325
#define DLG_SYS_PREVIEW                 326
#define IDR_TOOLBAR2                    327
#define ICON_PREVIEW                    329
#define BMP_BACK                        330
#define IDD_FORMVIEW                    331
#define IDD_FORM_IMPORT                 331
#define IDI_KEY                         335
#define IDI_CANCLE                      336
#define IDI_RADIO                       339
#define IDI_LINK                        340
#define IDI_ROLL_ALL                    342
#define IDI_ROLL_SINGLE                 343
#define IDI_ROOLING                     344
#define IDI_SPESH                       346
#define IDI_SINGLE                      349
#define IDI_IMPORT                      350
#define IDI_SEARCH                      351
#define IDI_SEARCH1                     352
#define IDI_CHOOSE                      353
#define IDB_FORMBACK                    355
#define IDI_OPEN                        356
#define IDI_CLOSE                       357
#define IDI_OP                          358
#define IDR_MAINFRA                     359
#define IDI_LOG                         364
#define IDI_SHOWALL                     367
#define IDI_SEARCHPAPER                 368
#define IDI_ADDPAPER                    369
#define IDI_CANCEL                      370
#define IDI_OK                          371
#define IDI_ROLL                        372
#define IDI_ICONING                     373
#define IDI_LATE                        374
#define IDI_LINKR                       375
#define IDI_BACK                        376
#define IDI_UP                          377
#define IDI_SP                          378
#define IDI_DEPART                      379
#define IDI_ANSWER                      380
#define IDI_PAPER                       381
#define IDI_TEACH                       382
#define IDI_PP                          383
#define IDI_SUB                         384
#define IDI_ADDANSWER                   386
#define IDI_PLUS                        387
#define IDI_SAVE                        388
#define IDI_DELETE                      389
#define IDI_UPDATE                      390
#define IDI_PRINT                       391
#define IDI_EXCEL                       392
#define IDI_CHART                       393
#define IDB_LOAD_OFF                    397
#define IDB_LOAD_ON                     398
#define IDB_LOAD_DOWN                   399
#define IDB_LOG_BACK                    400
#define IDB_LOAD_MASK                   401
#define IDB_EXIT_DOWN                   402
#define IDB_EXIT_OFF                    403
#define IDB_EXIT_ON                     404
#define IDB_SEARCH_DOWN                 405
#define IDB_SEARCH_OFF                  406
#define IDB_SEARCH_ON                   407
#define IDB_MASK                        408
#define IDB_CHOOSE_DOWN                 409
#define IDB_CHOOSE_OFF                  410
#define IDB_CHOOSE_ON                   411
#define IDB_BITMAP3                     412
#define IDB_LOG_IN                      412
#define IDB_LOG_IN_OVER                 413
#define IDB_EXIT                        414
#define IDB_EXIT_OVER                   415
#define IDB_MENU                        418
#define IDB_DATE_DOWN                   422
#define IDB_DATE                        423
#define IDB_EXAM_DOWN                   425
#define IDB_EXAM                        426
#define IDB_QUERY_DOWN                  427
#define IDB_QUERY                       428
#define IDB_EXIT_BN                     430
#define IDB_SEARCH                      432
#define IDB_BN_BACK                     433
#define IDB_CHOOSE                      435
#define IDB_OPENFM_DOWN                 436
#define IDB_OPENFM                      437
#define IDB_CLOSEFM_DOWN                438
#define IDB_CLOSEFM                     439
#define IDB_SEARCHFM_DOWN               440
#define IDB_SEARCHFM                    441
#define IDB_UPFM_DOWN                   442
#define IDB_UPFM                        443
#define IDB_DOWNFM_DOWN                 444
#define IDB_DOWNFM                      445
#define IDB_INPUTFM_DOWN                446
#define IDB_INPUTFM                     447
#define IDD_FORM_EXAM_MODE              448
#define IDB_MAIN                        449
#define IDD_FORM_EXAMSET                450
#define IDB_LOGIN                       452
#define IDB_LOGIN_DOWN                  453
#define IDB_EXIT_LOG_BN_DOWN            454
#define IDB_EXIT_LOG_BN                 455
#define IDB_1280_800                    456
#define IDB_MENU1                       457
#define IDB_MAIN1                       458
#define IDD_FORM_LISTEN                 459
#define IDD_CHANGESYSTIME               460
#define IDD_FORM_IMAGE                  461
#define IDB_SHOWALL_DOWN                462
#define IDB_SHOWALL                     463
#define IDB_PAPERQUERY_DOWN             464
#define IDB_PAPERQUERY                  465
#define IDB_ADDANSWER_DOWN              466
#define IDB_ADDANSWER                   467
#define IDB_ADD_DOWN                    468
#define IDB_ADD                         469
#define IDB_DELETE_DOWN                 470
#define IDB_DELETE                      471
#define IDB_UPDATE                      472
#define IDB_UPDATE_DOWN                 473
#define IDB_SAVE_DOWN                   474
#define IDB_SAVE                        475
#define IDB_QUERY_DOWN1                 476
#define IDB_QUERY1                      477
#define IDB_STATIC_DOWN                 478
#define IDB_STATIC                      479
#define IDB_REPORT_DOWN                 480
#define IDB_REPORT                      481
#define IDB_PRINT_DOWN                  482
#define IDB_PRINT                       483
#define IDD_FORM_EXAM_BLUE              484
#define IDB_NEXT_DOWN                   485
#define IDB_NEXT                        486
#define IDB_ADDPAPER_DOWN               487
#define IDB_ADDPAPER                    488
#define IDB_UP_DOWN                     489
#define IDB_UP                          490
#define IDB_CHANGESYSTIME_DOWN          491
#define IDB_CHANGESYSTIME               492
#define IDB_ROLL_DOWN                   493
#define IDB_ROLL                        494
#define IDB_SEARCH_GRAY                 495
#define IDB_ROLLING_DOWN                496
#define IDB_ROLLING                     497
#define IDB_ADDDEPART_DOWN              498
#define IDB_ADDDEPART                   499
#define IDB_ADDCLASS_DOWN               500
#define IDB_ADDCLASS                    501
#define IDB_UPDATEDEPART_DOWN           502
#define IDB_UPDATEDEPART                503
#define IDB_UPDATECLASS_DOWN            504
#define IDB_UPDATECLASS                 505
#define IDB_DELETECLASS_DOWN            506
#define IDB_DELETECLASS                 507
#define IDB_DELETEDEPART_DOWN           510
#define IDB_DELETEDEPART                511
#define IDD_FORM_EXAM_INFRAR            512
#define IDB_OK_DOWN                     513
#define IDB_OK                          514
#define IDD_FORM_EXAM_USB               515
#define IDD_FORM_EXAM_TIME              516
#define IDD_CHANGE_EXAM_TIME            517
#define IDB_CHANGE_EXAM_TIME_DOWN       518
#define IDB_CHANGE_EXAM_TIME            519
#define IDB_UP_GRAY                     520
#define IDB_ROLL_GRAY                   521
#define IDD_FORM_STU_RESULT_QUERY       522
#define IDB_PRINTCHART_DOWN             524
#define IDB_PRINTCHART                  525
#define IDD_FORM_CLASS_RESULT_QUERY     527
#define IDD_TEACHER_SET                 529
#define IDD_FORM_PAPER_ANALY            530
#define IDD_DLG_PAPER_ANALY             532
#define IDB_EXPORT_CHART_DOWN           533
#define IDB_EXPORT_CHART                534
#define IDD_FORM_IMAGE_READ             535
#define IDB_BBB                         536
#define IDB_SET_DOWN                    537
#define IDB_SET                         538
#define IDB_BACK                        539
#define IDB_LOGIN_DOWN1                 540
#define IDB_LOGIN1                      541
#define IDB_EXIT_DOWN1                  542
#define IDB_EXIT1                       543
#define IDB_MENU2                       544
#define IDB_BACK2                       546
#define IDB_MAIN2                       547
#define IDD_FORM_EXAM_DETAIL            548
#define IDD_FORM_EXMA_INFO_BACK         549
#define IDD_FORM_CREAT_FILE             550
#define IDD_DLG_EXAM_EDIT               551
#define IDD_FORM_EXAM_IMPORT            552
#define IDD_DLG_ROLLING_CHOOSE          553
#define IDD_FORM_EXAM_INRARA_OFF        554
#define IDD_FORM_ROLLING_INRAR_ANSWER   555
#define IDC_LIST                        1001
#define IDC_DATE_FROM                   1004
#define IDC_DATE_FROM2                  1005
#define IDC_EDIT                        1006
#define IDC_KIND                        1007
#define IDC_GROUP                       1009
#define IDC_STARTIP                     1010
#define IDC_STATIC4                     1010
#define IDC_ENDIP                       1011
#define IDC_EDIT1                       1012
#define IDC_STUNAME                     1012
#define IDC_SUPERVISOR                  1012
#define IDC_ID                          1012
#define IDC_TEACHERID                   1012
#define IDC_CLASSID                     1012
#define IDC_STUDID                      1012
#define IDC_START_NO                    1012
#define IDC_CHANNEL                     1012
#define EDT_GOTO                        1012
#define IDC_EDIT2                       1013
#define IDC_KEY                         1013
#define IDC_HEAD                        1013
#define IDC_EMIAL                       1013
#define IDC_TEACHER                     1013
#define IDC_STUID                       1013
#define IDC_ACCOUNT                     1013
#define IDC_DEV                         1013
#define IDC_TEACHERNAME                 1013
#define IDC_END                         1013
#define IDC_STUDNAME                    1013
#define IDC_END_NO                      1013
#define IDC_EDIT3                       1014
#define IDC_ALL                         1014
#define IDC_MSG                         1014
#define IDC_TEL                         1014
#define IDC_STUNUM                      1014
#define IDC_DEVID                       1014
#define IDC_TOPICNUM                    1014
#define IDC_TEACHERDEV                  1014
#define IDC_MAXNO                       1014
#define IDC_MAX_NO                      1014
#define IDC_DALL                        1015
#define IDC_DEALL                       1015
#define IDC_DEPARTMENT                  1015
#define IDC_DEPART                      1015
#define IDC_STARTNO                     1015
#define IDC_STOP                        1016
#define IDC_ENDNO                       1016
#define IDC_LATESEARCH                  1016
#define IDC_DEPARTID                    1016
#define IDC_BLUETEETH                   1016
#define IDC_DEPARTMENTSTATIC            1016
#define IDC_PROGRESS1                   1017
#define IDC_USE                         1017
#define IDC_LATESTART                   1017
#define IDC_READ_ACCOUNT                1018
#define IDC_LATE                        1018
#define IDC_IPADDRESS1                  1019
#define IDC_IPADDRESS                   1019
#define IDC_IP                          1019
#define IDC_PREROLLING                  1019
#define IDC_IP2                         1020
#define IDC_IPADDRESS2                  1020
#define IDC_SPEROLL                     1020
#define IDC_ADD                         1021
#define IDC_LINKROLLING                 1021
#define IDC_QUERY                       1022
#define IDC_LINKROLL                    1022
#define IDC_ADDCLASS                    1022
#define IDC_SHOWALL                     1022
#define IDC_SATA                        1023
#define IDC_UPDATEDEPART                1023
#define IDC_NORMAL                      1024
#define IDC_UPDATECLASS                 1024
#define IDC_DELETE                      1025
#define IDC_UPLOAD                      1026
#define IDC_UPDATE                      1026
#define IDC_COMBO                       1027
#define IDC_DISPLAY                     1027
#define IDC_DIRECT                      1028
#define IDC_APP                         1028
#define IDC_DELETEDEPART                1028
#define IDC_IS_IP_RANGE                 1029
#define IDC_DELETECLASS                 1029
#define IDC_PROTO                       1030
#define IDC_IS_PORT_RANGE               1031
#define IDC_NAME                        1032
#define IDC_IP1                         1033
#define IDC_CLASS                       1033
#define IDC_IDNUM                       1033
#define IDC_PORT1                       1034
#define IDC_CLASSHEAD                   1034
#define IDC_PORT2                       1035
#define IDC_CLASSHEADTEL                1035
#define IDC_TEXT1                       1036
#define IDC_TEXT2                       1037
#define IDC_TEXT3                       1038
#define IDC_TEXT4                       1039
#define IDC_CHECK1                      1042
#define IDC_CHECKSUBJECT                1042
#define IDC_CHECK2                      1043
#define IDC_CHECKDEPART                 1043
#define IDC_CHECK3                      1044
#define IDC_CHECKTIME                   1044
#define IDC_CHECK4                      1045
#define IDC_LIST_TIME                   1045
#define IDC_CHECK5                      1046
#define IDC_LIST_DATE                   1046
#define IDC_CHECK6                      1047
#define IDC_MAC                         1047
#define IDC_CHECK7                      1048
#define IDC_DATETIMEPICKER1             1048
#define IDC_STARTDATE                   1048
#define IDC_DATETIMEPICKER              1048
#define IDC_START1                      1048
#define IDC_END_TIME                    1048
#define IDC_DATETIMEPICKER2             1049
#define IDC_TEXT                        1049
#define IDC_CHECK9                      1049
#define IDC_STARTTIME                   1049
#define IDC_END1                        1049
#define IDC_START_TIME                  1049
#define IDC_DATA                        1050
#define IDC_CHECK8                      1050
#define IDC_ENDTIME                     1050
#define IDC_PASS                        1050
#define IDC_ENDDATE                     1050
#define IDC_START2                      1050
#define IDC_IS_WEB                      1051
#define IDC_TEXT5                       1051
#define IDC_ENDTIM                      1051
#define IDC_END2                        1051
#define IDC_IS_MAC                      1052
#define IDC_DATA2                       1052
#define IDC_USER                        1052
#define IDC_START3                      1052
#define IDC_IS_KEY                      1053
#define IDC_END3                        1053
#define IDC_PERMIT                      1054
#define IDC_SHUT_DOWN                   1056
#define IDC_GET_TIME                    1057
#define IDC_SET_TIME                    1058
#define IDC_SET_CONFIG                  1059
#define IDC_GET_CONFIG                  1060
#define IDC_PROGRESS                    1061
#define IDC_UP_FILE                     1061
#define IDC_DOWN_FILE                   1062
#define IDC_TIMELEFT                    1063
#define IDC_MASK                        1063
#define IDC_GATE_WAY                    1064
#define IDC_DNS                         1065
#define IDC_TIME                        1067
#define IDC_PASS1                       1068
#define IDC_PASS2                       1069
#define IDT_NAME                        1070
#define IDT_TIME                        1071
#define IDT_IP                          1072
#define IDT_MASK                        1073
#define IDT_GATE_WAY                    1074
#define IDT_DNS                         1075
#define IDT_DATA                        1076
#define IDT_PASS2                       1077
#define IDT_PASS1                       1078
#define IDC_REFRESH                     1079
#define IDC_SAVE                        1080
#define IDC_TIME1                       1081
#define IDC_CTRL                        1082
#define IDC_STATIC3                     1082
#define IDC_TIME2                       1082
#define IDC_REBOOT                      1083
#define IDC_RELOAD                      1084
#define IDC_STATIC15                    1084
#define IDT_HARD_IP                     1085
#define IDC_STATIC2                     1085
#define IDT_SPOOL1                      1086
#define IDC_STATIC5                     1086
#define IDT_SPOOL                       1087
#define IDC_STATIC17                    1087
#define IDC_RECORD                      1088
#define IDC_SPOOL                       1089
#define IDC_HIP                         1090
#define IDC_ISPACKET                    1091
#define IDC_PACKET_SPOOL                1092
#define IDT_SPOOL2                      1093
#define IDC_SKYGRAPHCTRLCTRL            1093
#define IDC_DATE1                       1095
#define IDC_DATE2                       1096
#define IDC_CDOMAIN                     1097
#define IDC_DOMAIN                      1098
#define IDC_CGROUP                      1099
#define IDC_CIP                         1100
#define IDC_CPORT                       1101
#define IDC_PORT                        1102
#define IDC_TDOMAIN                     1103
#define IDC_TGROUP                      1104
#define IDC_TIP                         1105
#define IDC_TPORT                       1106
#define IDC_DEL_LOG                     1107
#define IDC_DELLOG                      1108
#define IDC_TCP_DOS                     1109
#define IDC_DDOS                        1110
#define IDC_IP_CHEAT                    1111
#define IDC_SYN                         1112
#define IDC_IP_CHEAT2                   1113
#define IDC_UDP_DOS                     1114
#define IDC_ICMP_DOS                    1115
#define IDC_ARP_CHEAT                   1116
#define IDC_TCP_CHEAT2                  1117
#define IDC_STATIC1                     1123
#define IDC_STATICX                     1124
#define IDC_STATIC12                    1124
#define IDC_STATICY                     1125
#define IDC_STATICZ                     1126
#define IDC_UPGRADE                     1127
#define IDC_TCP                         1128
#define IDC_UDP                         1129
#define IDC_COMPRESS                    1130
#define IDC_MEM                         1131
#define IDC_TMEM                        1132
#define IDC_DETAIL                      1133
#define IDC_SUPPER                      1134
#define IDC_TROCXTCCTRL1                1135
#define IDC_APPLY                       1136
#define IDC_SET_APP                     1139
#define IDC_SAVE_LOG                    1140
#define IDC_CTROCXNATCTRL1              1141
#define IDC_RUN                         1143
#define IDC_VAR                         1144
#define IDC_NUM                         1145
#define IDC_TROCXNATCTRL1               1148
#define IDC_BACK_CONFIG                 1149
#define IDC_BACK_RESTORE                1150
#define IDC_STATIC6                     1151
#define IDC_CM_KIND_PROXY               1152
#define IDC_TPROXY_KIND                 1153
#define IDC_ACTION                      1156
#define IDC_SYSTIME                     1158
#define IDC_STATI1                      1159
#define IDC_GUSER                       1171
#define IDC_COMBO1                      1172
#define IDC_GENDER                      1172
#define IDC_SUBJECT                     1172
#define IDC_TDEPARTMEN                  1173
#define IDC_ADDR                        1173
#define IDC_SUBJECTID                   1173
#define IDC_CHECK10                     1174
#define IDC_EXAMCLASS                   1174
#define IDC_ADDRID                      1174
#define IDC_BUTTON1                     1175
#define IDC_ROLL                        1175
#define IDC_OK                          1175
#define IDC_TEST                        1175
#define IDC_SUB                         1175
#define IDC_BUTTON2                     1176
#define IDC_START                       1176
#define IDC_CHOOSE                      1176
#define IDC_ADDANSWER                   1176
#define IDC_PAPER                       1176
#define IDC_SHOW                        1176
#define IDC_CLOSE                       1176
#define IDC_DATE                        1176
#define IDC_CLOSE_CAMERA                1176
#define IDC_EXPORT_CHART                1176
#define IDC_ROLLING                     1177
#define IDC_QUERYSTUD                   1177
#define IDC_ADDPAPER                    1177
#define IDC_BUTTON4                     1177
#define IDC_BUTTON3                     1178
#define IDC_SENDMESSAGE                 1178
#define IDC_ADDSTUD                     1178
#define IDC_FETCH                       1178
#define IDC_BACK                        1178
#define IDC_CATCH                       1178
#define IDC_ROLLCALL                    1178
#define IDC_PRINT_REPORT                1178
#define IDC_REVO                        1178
#define IDC_CHANGE_FM3                  1178
#define IDC_STATICN                     1179
#define IDC_SETTING                     1179
#define IDC_DELETESTUD                  1179
#define IDC_SEARCH                      1180
#define IDC_UPDATESTUD                  1180
#define IDC_CMAX_MB2                    1181
#define IDC_IMPORTCLASS                 1181
#define IDC_CMAX_KB2                    1182
#define IDC_CMIN_MB2                    1183
#define IDC_CMIN_KB2                    1184
#define IDC_LIST1                       1185
#define IDC_STULIST                     1185
#define IDC_DEPARTMENTLIST              1185
#define IDC_STDANSWERLIST               1185
#define IDC_RESULTLIST                  1185
#define IDC_PAPERLIST                   1185
#define IDC_PRINT1                      1186
#define IDC_SAVEAS                      1187
#define IDC_COMPUTER                    1190
#define IDC_LOAD                        1191
#define IDC_APPEAR                      1192
#define IDC_INIT                        1193
#define IDC_ALL_CTRL                    1194
#define IDC_DE_ALL_CTRL                 1195
#define IDC_BROWS                       1196
#define IDC_RANK                        1197
#define IDC_DEVLIST                     1199
#define IDC_NUMBER                      1200
#define IDC_NUMBER2                     1201
#define IDC_ADDRESS                     1222
#define IDC_PHOTO                       1223
#define IDC_SUBJECTLIST                 1225
#define IDC_STATIC7                     1228
#define IDC_EMAIL                       1229
#define IDC_STATE                       1230
#define IDC_ADDRLIST                    1231
#define IDC_STATIC8                     1232
#define IDC_STATIC9                     1233
#define IDC_STATIC10                    1234
#define IDC_CLASSLIST                   1236
#define IDC_STATIC11                    1237
#define IDC_LATELIST                    1238
#define IDC_REMIND                      1239
#define IDC_RESLIST                     1240
#define IDC_STATIC_ID                   1241
#define IDC_STATIC_NAME                 1242
#define IDC_STATIC_SUBJECT              1243
#define IDC_STATIC_PAPER                1244
#define IDC_STATIC_RIGHT                1245
#define IDC_STATIC_WRONG                1246
#define IDC_STATIC_TOTAL                1247
#define IDC_STATIC_RESULT               1248
#define IDC_SHOCKWAVEFLASH1             1249
#define IDC_ADDDEPART                   1257
#define IDC_RADIOSTUID                  1259
#define IDC_RADIOSTUNAME                1260
#define IDC_RADIOCLASS                  1261
#define IDC_CLASSSTATIC                 1262
#define IDC_QUERYPAPER                  1263
#define IDC_PAPERNAME                   1264
#define IDC_DELETEPAPER                 1264
#define IDC_ANSWERLIST                  1266
#define IDC_EXAMLIST                    1267
#define IDC_SEACH                       1268
#define IDC_LINKLIST                    1269
#define IDC_SUBJECTRADIO                1271
#define IDC_STUDNUM                     1274
#define IDC_PAPERQUERY                  1279
#define IDC_CLASSQUERY                  1280
#define IDC_TEACHLIST                   1281
#define IDC_CHOSE                       1283
#define IDC_UP                          1284
#define IDC_DOWN                        1285
#define IDC_OP                          1286
#define IDC_OPEN                        1287
#define SPIN_GOTO                       1288
#define BTN_OK                          1289
#define BTN_CANCEL                      1290
#define IDC_SUP                         1291
#define IDC_SDOWN                       1292
#define IDC_STATIC13                    1295
#define IDC_STATIC14                    1296
#define IDC_GRAPH_TYPE                  1298
#define IDC_LIST2                       1299
#define IDC_NEXT                        1300
#define IDC_EXIT                        1302
#define IDC_EXAM                        1303
#define IDC_RADIO_BLUE                  1306
#define IDC_RADIO_INFRA                 1307
#define IDC_RADIO_USB                   1308
#define IDC_RADIOYES                    1311
#define IDC_RADIONO                     1312
#define IDC_CHANGESYSTIME               1313
#define IDC_OPEN_CAMERA                 1314
#define IDC_STATIC16                    1317
#define IDC_STATIC18                    1318
#define IDC_STATIC19                    1319
#define IDC_STATIC20                    1320
#define IDC_STATIC21                    1321
#define IDC_STATIC22                    1322
#define IDC_STATIC23                    1323
#define IDC_STATIC24                    1324
#define IDC_STATIC25                    1325
#define IDC_STATIC26                    1326
#define IDC_CHANGE                      1327
#define IDC_CHART                       1328
#define IDC_PRINT_CHART                 1329
#define IDC_EXPORT_REPORT               1330
#define IDC_SET                         1334
#define IDC_CHOOSE1                     1335
#define IDC_PRINTREPORT                 1338
#define IDC_EXPORTREPORT                1339
#define IDC_OPNE                        1341
#define IDC_RADIO_STANDARD              1342
#define IDC_RADIO_NORMAL                1343
#define IDC_RADIO_BLUE2                 1345
#define IDC_RADIO_INFRA2                1346
#define IDC_RADIO_USB2                  1347
#define IDC_CREATE                      1349
#define IDC_FM                          1350
#define IDC_RADIO_ROLL_BLUE             1351
#define IDC_RADIO_ROLL_INFRAR           1352
#define IDC_RADIO_ROLL_USB              1353
#define IDC_RADIO_ROLLING_BLUE          1354
#define IDC_RADIO_ROLLING_INFRAR        1355
#define IDC_RADIO_ROLLING_USB           1356
#define IDC_RADIO_YES                   1359
#define IDC_RADIO_NO                    1360
#define IDC_CHANNLE                     1361
#define IDC_CHANGE_TIME                 1362
#define IDC_FM1                         1363
#define IDC_CHANGE_FM1                  1364
#define IDC_FM2                         1365
#define IDC_CHANGE_FM2                  1366
#define IDC_FM3                         1367
#define IDC_STULIST1                    1368
#define IDC_RADIO_LINK                  1369
#define IDC_RADIO_OFFLIN                1370
#define IDC_RADIO_QUERY                 1371
#define IDC_SENDINFO                    1373
#define IDC_FETCH1                      1374
#define IDC_STULIST2                    1376
#define IDC_SHOWCHART                   1377
#define IDC_CMIN_MB                     2011
#define IDM_ALL                         32774
#define IDM_DALL                        32775
#define IDM_OPEN                        32776
#define IDM_DELETE                      32777
#define IDM_STOP                        32778
#define IDM_PASS                        32779
#define IDM_ADD_IP                      32780
#define IDM_MOVE                        32781
#define IDM_CONFIG                      32782
#define IDM_WEB                         32783
#define IDM_PASS_WEB                    32785
#define IDM_NORMAL                      32786
#define IDM_RE_CHECK                    32787
#define IDM_HELP                        32789
#define IDM_KEY                         32790
#define IDM_CTRL                        32796
#define IDM_SUB                         32797
#define IDM_PRINT                       32798
#define IDM_MAIN                        32800
#define IDM_REPORT                      32801
#define IDM_BACKUP                      32802
#define IDM_RESTORE                     32803
#define IDM_FORMAT                      32805
#define IDM_SERVER                      32806
#define IDM_SAFE_REPORT                 32808
#define ID_EXPANSION                    32810
#define ID_APP_SETUSER                  32814
#define AFX_ID_IN                       32815
#define IDD_CHANGEPASS                  32816
#define ID_SHOWLEFTBAR                  32817
#define ID_SHOWBOTTOMBAR                32818
#define ID_SETPASS                      32819
#define ID_SETUSER                      32820
#define IDD_GETLOG                      32821
#define IDM_LOG                         32823
#define IDM_ON_LINE                     32825
#define IDM_FILTER                      32826
#define ID_EXAM                         32830
#define ID_DATA                         32831
#define ID_QUERY                        32832
#define ID_BUTTON32833                  32833
#define IDM_EXAM                        32833
#define TBTN_TOP                        32834
#define TBTN_PREVIOUS                   32835
#define TBTN_GOTO                       32836
#define TBTN_NEXT                       32837
#define TBTN_LAST                       32838
#define TBTN_EXIT                       32839
#define TBTN_PRINT                      32840
#define IDM_DATE                        32849
#define IDC_MYTREECTRL                  61446
#define IDM_HUN                         61447
#define IDS_STRING61448                 61448

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        556
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1379
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
