// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mschart_paperansys.h"

/////////////////////////////////////////////////////////////////////////////
// CMschart_paperansys

IMPLEMENT_DYNCREATE(CMschart_paperansys, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMschart_paperansys properties

/////////////////////////////////////////////////////////////////////////////
// CMschart_paperansys operations
