//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by YDUIExamOperate.rc
//
#define ID_RESDETAIL_OUTPUT             3
#define ID_BUTTON_EDIT_ANSWER           3
#define IDD_YDUIEXAMd_FORM_EXAM_INFRARED 102
#define IDD_YDUIEXAM_FORM_EXAM_INFRARED 102
#define IDI_WEB                         131
#define IDD_YDUIEXAM_DLG_PROGRESS       137
#define IDD_YDUIEXAM_OPERATE_FORM_TEACHER 273
#define IDD_YDUIEXAM_DIG_EXAM_STAT      287
#define IDD_YDUIEXAM_DLG_ONLINE_BEGINEXAM 291
#define IDD_YDUIEXAM_DLG_ONLINE_ROLLING 292
#define IDD_YDUIEXAM_DIG_RES_DETAIL     296
#define IDD_YDUIEXAM_DLG_PAPER_SET      311
#define IDD_YDUIEXAM_DLG_PAPER_QUERY    312
#define IDD_YDUIEXAM_FORM_FM            322
#define IDD_YDUIEXAM_DLG_FM             323
#define IDI_RADIO                       339
#define IDI_LINK                        340
#define IDI_ROLL_ALL                    342
#define IDI_ROLL_SINGLE                 343
#define IDI_ROOLING                     344
#define IDI_SPESH                       346
#define IDI_SINGLE                      349
#define IDI_IMPORT                      350
#define IDI_DEPART                      379
#define IDI_ANSWER                      380
#define IDI_PAPER                       381
#define IDI_TEACH                       382
#define IDI_PP                          383
#define IDI_SUB                         384
#define IDB_SEARCH_DOWN                 405
#define IDB_CHOOSE_DOWN                 409
#define IDB_SEARCH                      432
#define IDB_CHOOSE                      435
#define IDB_OPENFM_DOWN                 436
#define IDB_OPENFM                      437
#define IDB_CLOSEFM_DOWN                438
#define IDB_CLOSEFM                     439
#define IDB_SEARCHFM_DOWN               440
#define IDB_SEARCHFM                    441
#define IDB_UPFM_DOWN                   442
#define IDB_UPFM                        443
#define IDB_DOWNFM_DOWN                 444
#define IDB_DOWNFM                      445
#define IDB_INPUTFM_DOWN                446
#define IDB_INPUTFM                     447
#define IDD_YDUIEXAM_FORM_EXAM_MODE     448
#define IDD_YDUIEXAM_FORM_EXAMSET       450
#define IDD_YDUIEXAM_FORM_LISTEN        459
#define IDD_YDUIEXAM_DLG_CHANGESYSTIME  460
#define IDD_YDUIEXAM_FORM_IMAGE         461
#define IDB_SHOWALL_DOWN                462
#define IDB_SHOWALL                     463
#define IDB_PAPERQUERY_DOWN             464
#define IDB_PAPERQUERY                  465
#define IDB_NEXT_DOWN                   485
#define IDB_NEXT                        486
#define IDB_ADDPAPER_DOWN               487
#define IDB_ADDPAPER                    488
#define IDB_UP_DOWN                     489
#define IDB_UP                          490
#define IDB_CHANGESYSTIME_DOWN          491
#define IDB_CHANGESYSTIME               492
#define IDB_ROLL_DOWN                   493
#define IDB_ROLL                        494
#define IDB_SEARCH_GRAY                 495
#define IDB_ROLLING_DOWN                496
#define IDB_ROLLING                     497
#define IDD_YDUIEXAM_FORM_EXAM_INFRAR   512
#define IDB_OK_DOWN                     513
#define IDB_OK                          514
#define IDD_YDUIEXAM_FORM_EXAM_USB      515
#define IDD_YDUIEXAM_FORM_EXAM_TIME     516
#define IDD_YDUIEXAM_DLG_CHANGE_EXAM_TIME 517
#define IDB_CHANGE_EXAM_TIME_DOWN       518
#define IDB_CHANGE_EXAM_TIME            519
#define IDB_UP_GRAY                     520
#define IDB_ROLL_GRAY                   521
#define IDD_YDUIEXAM_DLG_TEACHER_SET    529
#define IDD_YDUIEXAM_FORM_IMAGE_READ    535
#define IDB_BBB                         536
#define IDB_SET_DOWN                    537
#define IDB_SET                         538
#define IDD_FORM_ROLLING_INRAR_ANSWER   555
#define IDD_YDUIEXAM_FORM_ROLLING_INRAR_ANSWER 555
#define IDD_YDUIEXAM_FORM_EXMA_INFO_BACK 560
#define IDC_LIST_STU                    1000
#define IDC_LIST                        1001
#define IDC_PORT                        1002
#define IDC_OPENPORT                    1003
#define IDC_BUTTON_OPENPORT             1003
#define IDC_START                       1004
#define IDC_BUTTON_START                1004
#define IDC_DATALIST                    1005
#define IDC_CLEAR_LIST                  1006
#define IDC_BUTTON_SEARCH_DEVICE        1007
#define IDC_CLEAR_BOX                   1008
#define IDC_STATIC4                     1010
#define IDC_CHANNEL                     1012
#define IDC_START_NO                    1012
#define IDC_EDIT1                       1012
#define IDC_TEACHER                     1013
#define IDC_END_NO                      1013
#define IDC_EDIT2                       1013
#define IDC_MAX_NO                      1014
#define IDC_EDIT3                       1014
#define IDC_DEPART                      1015
#define IDC_END_NO1                     1015
#define IDC_START_NO2                   1016
#define IDC_END_NO2                     1017
#define IDC_READ_ACCOUNT                1018
#define IDC_START_NO3                   1018
#define IDC_END_NO3                     1019
#define IDC_LINKROLLING                 1021
#define IDC_SHOWALL                     1022
#define IDC_                            1022
#define IDC_BUTTON_ONLINE_BEGINEXAM     1022
#define IDC_CLASS                       1033
#define IDC_CHECKSUBJECT                1042
#define IDC_CHECK1                      1042
#define IDC_CHECKDEPART                 1043
#define IDC_CHECK2                      1043
#define IDC_CHECKTIME                   1044
#define IDC_CHECK3                      1044
#define IDC_CHECK_PROGRAM_ONE           1045
#define IDC_CHECK_PROGRAM_TWO           1046
#define IDC_CHECK_PROGRAM_THREE         1047
#define IDC_DATETIMEPICKER              1048
#define IDC_STARTDATE                   1048
#define IDC_END_TIME                    1048
#define IDC_START1                      1048
#define IDC_STARTTIME                   1049
#define IDC_START_TIME                  1049
#define IDC_END1                        1049
#define IDC_ENDDATE                     1050
#define IDC_START2                      1050
#define IDC_ENDTIM                      1051
#define IDC_END2                        1051
#define IDC_START3                      1052
#define IDC_END3                        1053
#define IDC_PROGRESS                    1061
#define IDC_TIMELEFT                    1063
#define IDC_TIME                        1067
#define IDC_SAVE                        1080
#define IDC_STATIC3                     1082
#define IDC_STATIC15                    1084
#define IDC_STATIC2                     1085
#define IDC_STATIC5                     1086
#define IDC_STATIC17                    1087
#define IDC_STATIC1                     1123
#define IDC_STATIC12                    1124
#define IDC_STATIC6                     1151
#define IDC_SUBJECT                     1172
#define IDC_ADDR                        1173
#define IDC_BUTTON1                     1175
#define IDC_OK                          1175
#define IDC_CHOOSE                      1176
#define IDC_CLOSE                       1176
#define IDC_DATE                        1176
#define IDC_CHOOSE2                     1176
#define IDC_CLOSE_CAMERA                1176
#define IDC_ADDPAPER                    1177
#define IDC_CHOOSE3                     1177
#define IDC_DATE_OP_ERRORREPORT_END     1177
#define IDC_ROLLCALL                    1178
#define IDC_REVO                        1178
#define IDC_CATCH                       1178
#define IDC_SEARCH                      1180
#define IDC_LIST1                       1185
#define IDC_PAPERLIST                   1185
#define IDC_STULIST                     1185
#define IDC_LIST_CLASS                  1185
#define IDC_LIST_DATA_OP_CHOICEANSYS    1185
#define IDC_LIST_MARKS                  1185
#define IDC_EXAM_TREE                   1186
#define IDC_EXAM_LIST_MSGBOX            1187
#define IDC_DEVLIST                     1199
#define IDC_STATIC7                     1228
#define IDC_STATIC8                     1232
#define IDC_STATIC9                     1233
#define IDC_STATIC10                    1234
#define IDC_CLASSLIST                   1236
#define IDC_STATIC11                    1237
#define IDC_RESLIST                     1240
#define IDC_SHOCKWAVEFLASH1             1249
#define IDC_PAPERNAME                   1264
#define IDC_EXAMLIST                    1267
#define IDC_SEACH                       1268
#define IDC_LINKLIST                    1269
#define IDC_PAPERQUERY                  1279
#define IDC_UP                          1284
#define IDC_DOWN                        1285
#define IDC_OP                          1286
#define IDC_OPEN                        1287
#define IDC_STATIC13                    1295
#define IDC_STATIC14                    1296
#define IDC_NEXT                        1300
#define IDC_RADIO_BLUE                  1306
#define IDC_RADIO_INFRA                 1307
#define IDC_RADIO_USB                   1308
#define IDC_RADIO_BLUE2                 1309
#define IDC_RADIO_INFRA2                1310
#define IDC_RADIO_USB2                  1311
#define IDC_RADIOYES                    1311
#define IDC_RADIONO                     1312
#define IDC_CHANGESYSTIME               1313
#define IDC_OPEN_CAMERA                 1314
#define IDC_STATIC16                    1317
#define IDC_STATIC18                    1318
#define IDC_STATIC19                    1319
#define IDC_STATIC20                    1320
#define IDC_STATIC21                    1321
#define IDC_STATIC22                    1322
#define IDC_STATIC23                    1323
#define IDC_STATIC24                    1324
#define IDC_STATIC25                    1325
#define IDC_STATIC26                    1326
#define IDC_CHANGE                      1327
#define IDC_SET                         1334
#define IDC_CHOOSE1                     1335
#define IDC_CHOOSE_TYPE1                1337
#define IDC_CHOOSE_TYPE2                1338
#define IDC_CHOOSE_TYPE3                1340
#define IDC_OPNE                        1341
#define IDC_RADIO_STANDARD              1342
#define IDC_RADIO_NORMAL                1343
#define IDC_FM                          1345
#define IDC_FETCH1                      1374
#define IDC_START_NO1                   1386
#define IDC_EDIT_FREQUENCY              16000
#define IDR_MENU_LIST_MSG               16000
#define IDD_YDUIEXAM_DLG_SEL_CLASS      16002
#define IDC_COMBO_EXAM_ROOM             16003
#define IDC_COMBO_EXAM_KIND             16004
#define IDC_COMBO_EXAM_PAPER            16005
#define IDC_DATETIMEPICKER_START        16007
#define IDC_DATETIMEPICKER_END          16008
#define IDR_MENU_LIST_ROLLCALL          16008
#define IDR_MENU_LIST_USB_STU           16008
#define IDC_FM_FREQUENCY                16009
#define IDD_YDUIEXAM_DLG_CHOICEANSYS    16009
#define IDC_EDIT_SYSTIME                16010
#define IDC_COMBO_EXAM_SUBJECT          16011
#define IDC_LIST_STUDENT2               16012
#define IDC_BUTTON_SEARCH               16013
#define IDR_MENU_LIST_MARK_ANA          16014
#define IDC_BUTTON_SEARCH2              16014
#define IDC_CHECK_LISTEN_ONE            16015
#define IDD_YDUIEXAM_DLG_ERROR_DETAIL   16015
#define IDC_CHECK_LISTEN_TWO            16016
#define IDD_YDUIEXAM_DLGSHOWCHART       16016
#define IDC_CHECK_LISTEN_THREE          16017
#define IDC_DATETIMEPICKER_LISTEN_ONE_START 16018
#define IDD_DLG_SHOWLIST                16018
#define IDC_DATETIMEPICKER_LISTEN_TWO_START 16019
#define IDD_YDUIEXAM_FORM_EXAM_BLUE     16019
#define IDC_DATETIMEPICKER_LISTEN_THREE_START 16020
#define IDC_DATETIMEPICKER_LISTEN_ONE_END 16021
#define IDD_YDUIEXAM_DLG_EXAM_BLUE_DETAIL 16021
#define IDC_DATETIMEPICKER_LISTEN_TWO_END 16022
#define IDC_DATETIMEPICKER_LISTEN_THREE_END 16023
#define IDD_YDUIEXAM_DLG_PAPER          16023
#define IDC_BUTTON_ROLLING              16024
#define IDR_HTML_PAGEROLLCALL           16025
#define IDC_BUTTON_INPUT                16025
#define IDC_BUTTON_QUERYMARK            16025
#define IDD_DIALOG1                     16025
#define IDD_YDUIEXAM_DLG_PAPER_EDIT_ANSWER 16025
#define IDC_BUTTON_SAVE                 16026
#define IDC_BUTTON_PAPER_ANSYS          16026
#define IDD_YDEXAM_DLG_INPUT_STUDENT_ANSWER_RECORD 16026
#define IDD_YDUIEXAM_DLG_INPUT_STUDENT_ANSWER_RECORD 16026
#define IDR_HTML_PAGEROLLCALL1          16027
#define IDC_CHOOSE_ANSWER1              16027
#define IDC_BUTTON_PAPER_ANS            16027
#define IDC_CHOOSE_ANSWER2              16028
#define IDC_CHOOSE_ANSWER3              16029
#define IDC_PROGRESS_STATUS             16030
#define IDC_STATIC_WAIT                 16031
#define IDC_BUTTON_BEGINEXAM            16032
#define IDC_EDIT_STUNO                  16033
#define IDC_EDIT_SUBJECT                16034
#define IDC_EDIT_PROGRESS               16034
#define IDC_EDIT_STUNAME                16035
#define IDC_CMB_OP_PAPERANSYS_PAPER     16035
#define IDC_EDIT_PAPER                  16036
#define IDC_CMB_OP_PAPERANSYS_DEPT      16036
#define IDC_EDIT_ERROR_ITEMNO           16037
#define IDC_LIST_OP_PAPERANSYS_ALL_CLASS 16037
#define IDC_EDIT_RIGHT_ITEMNO           16038
#define IDC_LIST_OP_PAPERANSYS_SEL_CLASS 16038
#define IDC_EDIT_TOTAL_SCORE            16039
#define IDC_BTN_OP_PAPERANSYS_ADD       16039
#define IDC_EDIT_SCORE                  16040
#define IDC_BTN_OP_PAPERANSYS_DEL       16040
#define IDC_LIST_OP_ERRORREPORT_LIST    16041
#define IDC_CMB_DATA_OP_SUBJECT         16042
#define IDC_CMB_OP_ERRORREPORT_SUBJECT  16042
#define IDC_DATE_OP_ERRORREPORT_BEGIN   16043
#define IDC_BTN_OP_ERRORREPORT_SEARCH   16044
#define IDC_CMB_OP_ERRORREPORT_PAPER    16045
#define IDC_BTN_OP_ERRORREPORT_SEARCH2  16046
#define IDC_MSCHART_PAPERANSYS          16048
#define IDC_MSCHART_MARKQUERY           16048
#define IDC_MSCHART_                    16049
#define IDC_BUTTON_CANCEL_PROGRESS      16050
#define IDC_BTN_OP_ERRORREPORT_OUTPUT   16051
#define IDC_STATIC_BK                   16053
#define IDC_EDIT_AVERAGE_MARK           16054
#define IDC_BTN_SHOWLIST                16055
#define IDC_BTN_SHOWCHART               16056
#define IDC_MSCHART_SHOW                16057
#define IDC_LIST_OP_MARK                16058
#define IDC_MSCHART_SHOW_PS             16059
#define IDC_EDIT_INFO                   16060
#define IDC_BUTTON_GET_STUDEV           16064
#define IDC_DATE_OP_QUERY_END           16065
#define IDC_DATE_OP_QUERY_BEGIN         16066
#define IDC_CHECK_SEL_ALL               16067
#define IDC_CHECK_SEL_INVERSE           16068
#define IDC_COMBO_DEV_COM               16068
#define IDC_EDIT_RECEIVE_STUNO          16070
#define IDC_BUTTON_DETAIL               16071
#define IDC_TEACHER_TEST                16072
#define IDC_TEACHER_CHOOSE              16073
#define IDC_BUTTON_NEW_PAPER            16074
#define IDC_COMBO_IN_SUBJECT            16074
#define IDC_BUTTONNEW_PAPER             16075
#define IDC_BUTTON_INPUT_FROM_XML       16076
#define IDD_YDUIEXAM_DATA_OP_PAPERANSYS 17000
#define IDC_LIST_OP_PAPERANSYS_MARK     17001
#define IDC_BTN_OP_PAPERANSYS_SEARCH    17005
#define IDC_BTN_OP_PAPERANSYS_OUTPUT    17006
#define IDD_YDUIEXAM_DATA_MAINTAIN_MARKQUERY 17011
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_QMARKBYSTU_SHEET 17012
#define IDD_YDUIEXAM_DATA_MAINTAIN_DLG_QMARKBYCLASS_SHEET 17013
#define IDD_YDUIEXAM_DATA_OP_ERRORREPORT 17014
#define IDD_DLG_SHOWLIST_PS             17015
#define IDD_YDUIEXAM_DLGSHOWCHART1      17016
#define IDD_YDUIEXAM_DLGSHOWCHART_PS    17016
#define IDC_DM_PAPER_CODE               17042
#define IDC_DM_PAPER_NAME               17043
#define IDC_BTN_DM_STU_ADDQC            17060
#define IDC_BTN_DM_STU_DELQC            17061
#define IDC_EDIT_BEGIN1                 17061
#define IDC_BTN_DM_STU_CLEARQC          17062
#define IDC_EDIT_END1                   17062
#define IDC_EDIT_COUNT1                 17063
#define IDC_EDIT_BEGIN2                 17064
#define IDC_CMB_MULTI1                  17065
#define IDC_EDIT_END2                   17066
#define IDC_EDIT_COUNT2                 17067
#define IDC_CMB_MULTI2                  17068
#define IDC_EDIT_BEGIN3                 17069
#define IDC_EDIT_END3                   17070
#define IDC_EDIT_COUNT3                 17071
#define IDC_CMB_MULTI3                  17072
#define IDC_DM_QMARK_TAB                17081
#define IDC_LIST_DM_QMARK_ALL_CLASS     17082
#define IDC_LIST_DM_QMARK_SEL_CLASS     17083
#define IDC_BTN_DM_QMARK_ADD            17084
#define IDC_BTN_DM_QMARK_DEL            17085
#define IDC_CMB_DM_QMARK_DEPT           17089
#define IDC_BTN_DM_QMARK_SEARCH         17090
#define IDC_EDIT_DM_QMARK_TOTAL         17091
#define IDC_EDIT_DM_QMARK_PAGENUM       17092
#define IDC_LIST_DM_QMARK_MARKS         17093
#define IDC_BTN_DM_QMARK_BEGIN          17094
#define IDC_BTN_DM_QMARK_PREV           17095
#define IDC_BTN_DM_QMARK_NEXT           17096
#define IDC_BTN_DM_QMARK_END            17097
#define IDC_CMB_DM_QMARK_PAPER          17098
#define IDC_STATIC_DM_QMARK_GRID        17099
#define IDC_CMB_DM_QMARK_SUBJECT        17099
#define IDC_BTN_DM_QMARK_OUTPUT         17100
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_MSG_DEL                      32774
#define ID_MSG_COPY                     32775
#define ID_MSG_CLEAR                    32776
#define ID_MI_MSG_DEL                   32777
#define ID_MI_MSG_COPY                  32778
#define ID_MI_MSG_CLEAR                 32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_MI_ROCALL_SPEC_FIND          32783
#define ID_MI_ROCALL_SPEC_ROLLCALL      32784
#define ID_MI_ROCALL_SPEC_ROLLING       32785
#define ID_32786                        32786
#define ID_32787                        32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_MI_ROCALL_SPEC_FIND_USB      32790
#define ID_MI_ROCALL_SPEC_BLUE          32791
#define ID_MI_ROCALL_SPEC_ROCALL_USB    32792
#define ID_MI_ROCALL_SPEC_ROCALL_BLUE   32793
#define ID_MI_ROCALL_SPEC_FIND_BLUE     32794
#define ID_MI_USB_ROLLCALL              32795
#define ID_MI_USB_BEGIN_EXAM            32796
#define ID_MI_USB_ROLLING               32797
#define ID_32798                        32798
#define ID_MI_STUMARK_ANA               32799
#define ID_32800                        32800
#define ID_MI_STU_DETAILINFO            32801
#define ID_32802                        32802
#define ID_MI_CONTINUE_BEGIN_EXAM       32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        16027
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         16077
#define _APS_NEXT_SYMED_VALUE           16028
#endif
#endif
