DELETE FROM ARTICLEQCHOICEQ
DELETE FROM ARTICLEQUESTION
DELETE FROM CHOICEQUESTION
DELETE FROM CPFOLDERHIERARCHY
DELETE FROM KNOWLEDGEPOINT
DELETE FROM MEDIA
DELETE FROM PAPER
DELETE FROM PAPERFOLDER
DELETE FROM PFOLDERHIERARCHY
DELETE FROM QCLASSIFICATIONQVAULT
DELETE FROM QUESTIONKPOINT
DELETE FROM QUESTIONMEDIA
DELETE FROM QUESTIONVAULT
DELETE FROM QVAULTCLASSIFICATION
DELETE FROM QVAULTKPOINT
DELETE FROM QVAULTQTYPE
DELETE FROM QVaultQuestion
DELETE FROM QVCLASSIFICATIONHIERARCHY



